namespace SwRebellionEditor
{
    public struct CapitalShip
    {
        public uint number;
        public uint unknown1;
        public uint prodFacilityNum;
        public uint unknown2;
        public uint familyNum;
        public ushort textstratNum;
        public ushort unknown3;
        public uint rebel;
        public uint empire;
        public uint conCost;
        public uint maintCost;
        public uint researchNum;
        public uint researchDiff;
        public uint unknown4;
        public uint detection;
        public uint shield;
        public uint sublight;
        public uint maneuverablity;
        public uint hyperdrive;
        public uint hyperdrive2;
        public uint firePowerArc1;
        public uint firePowerArc2;
        public uint firePowerArc3;
        public uint firePowerArc4;
        public uint firePowerArc5;
        public uint firePowerArc6;
        public uint firePowerArc7;
        public uint firePowerArc8;
        public uint firePowerArc9;
        public uint firePowerArc10;
        public uint firePowerArc11;
        public uint firePowerArc12;
        public uint turboLaserRange;
        public uint ionRange;
        public uint laserRange;
        public uint sumTurboLaserFP;
        public uint sumIonFP;
        public uint sumLaserFP;
        public uint sumFP;
        public uint hull;
        public uint tractorBeamPower;
        public uint tractorBeamRange;
        public uint gravity1;
        public uint gravity2;
        public uint bombardment;
        public uint damageControl;
        public uint weaponRecharge;
        public uint shieldRecharge;
        public uint fighterSquad;
        public uint troops;
        public uint unknown5;
        public string swrName;
        public string swrEncyText;
    }
}
