namespace SwRebellionEditor;

// WAVE, Bitmap, RCData, Version Info, 302

public class Alsprite : ResourcesDll
{
    public Alsprite(string fileName) : base(fileName)
    {
        NamesBitmap = new Dictionary<string, string>
            {
                { "2001", "c3p0" },
                { "2041", "c3p0" },
                { "2301", "c3p0" },
                { "2401", "c3p0" },
                { "2511", "c3p0" },
                { "2551", "c3p0" },
                { "2651", "c3p0" },
                { "2751", "c3p0" },
                { "2901", "c3p0" },
                { "2941", "c3p0" },
                { "3002", "c3p0" },
                { "3100", "c3p0" },
                { "3331", "r2d2" },
                { "3370", "r2d2" },
                { "3400", "c3p0" },
                { "3460", "c3p0" },
                { "3511", "c3p0" },
                { "3531", "c3p0" },
                { "3770", "c3p0" },
                { "3800", "c3p0" },
                { "3900", "c3p0" },
                { "16000", "c3p0" },
                { "16100", "c3p0" },
                { "16150", "c3p0" },
                { "16200", "c3p0" },
                { "16250", "c3p0" },
                { "16300", "c3p0" },
                { "16350", "c3p0" },
                { "16400", "c3p0" },
                { "16450", "c3p0" },
                { "16500", "c3p0" },
                { "16600", "c3p0" },
                { "19600", "c3p0" },
                { "19910", "c3p0" },
                { "19630", "c3p0" },
                { "19650", "c3p0" },
                { "19670", "c3p0" },
                { "19690", "c3p0" },
            };
        NamesWave = new Dictionary<string, string>
            {
                { "1017", "well, if you'll not be needing me, i'll close down for a while" },
                { "1018", "oh, ah, ah, yes, i am here" },
                { "1056", "oh dear, captain solo has been captured" },
                { "1058", "princess leia has been capture, oh my" },
                { "1078", "a capture of darth vader is excellent news" },
                { "1079", "we've captured the emperor, this is certainly good news" },
                { "1080", "oh no, darth vader has escaped" },
                { "1081", "the emperor has escaped, we're doomed" },
                { "1084", "oh dear, president mon mothma has been captured by the empire, we must rescue the president" },
                { "1085", "oh no, master luke has been captured, we've got to find him and send a rescue mission" },
                { "1086", "president mon mothma is free of the empire" },
                { "1087", "luke skywalker has escaped, i never doubted he would" },
                { "1093", "imperial ships" },
                { "1094", "the empire is defeated, we've done it" },
                { "1096", "may i remind you that no messages may be sent to units in hyperspace, i'm afraid you'll have to wait until those units arrive at their destination" },
                { "1097", "units can only be deployed to a system we control" },
                { "1098", "there are units assigned to the mission which are not capable of acting on the assigned target, i'm afraid no mission could be formed" },
                { "1099", "personnel cannot be assigned to missions with reconnaissance units" },
                { "1100", "damage to one or more ships in the fleet, prevents them from entering hyperspace" },
                { "1101", "that system has been destroyed by the empire, we can't send anyone there" },
                { "1102", "excuse me, but that ship class is not capable of carrying those type of units" },
                { "1103", "i'm sorry, unfortunately, that fleet does not have sufficient capacity to hold all of those units" },
                { "1104", "i'm sorry, unfortunately, that fleet is filled to capacity, i'm afraid your order cannot be carried out" },
                { "1105", "i'm sorry, your order to build that new unit cannot be carried out, we don't have the maintenance capacity to support it" },
                { "1106", "i'm afraid there is not enough energy available in that system, you must have free energy for each new facility" },
                { "1107", "i'm afraid but there are not enough raw materials, you must have untapped raw materials for each new mine" },
                { "1108", "i'm afraid there is not enough energy available in that system to deploy another facility there" },
                { "1109", "i'm sorry, there are no more raw materials available for exploitation on that system" },
                { "1110", "might i enquire, what is going on" },
                { "1111", "sometimes i just don't understand human behavior" },
                { "1113", "there are messages waiting, r2 is holding them for you" },
                { "1114", "r2 says there's a message coming in from a planetary system" },
                { "1115", "r2 indicates that a manufacturing message has been received" },
                { "1116", "there is a message from maintenance that requires your immediate attention" },
                { "1117", "r2 says that research and development is transmitting a message" },
                { "1118", "r2 has good news from support for the alliance" },
                { "1119", "i'm afraid r2 has some bad news about support for the alliance" },
                { "1124", "r2 says one of our agents is reporting in" },
                { "1126", "there is a message from the president" },
                { "1127", "there is a message from princess leia" },
                { "1128", "there is a message from master luke" },
                { "1129", "there is a message from captain solo" },
                { "1131", "i am fluent in 6 millions forms of communication, this signal is not used by the alliance, it could be an imperial code" },
                { "1132", "certainly" },
                { "1133", "i'm afraid we do not have the appropriate manufacturing facilities available" },
                { "1137", "you want me to supervise our planetary garrisons" },
                { "1138", "i'll be happy to relinquish control of our planetary garrisons to you" },
                { "1139", "i shall attempt to maximize the output of our mines and refineries" },
                { "1140", "i hope you found my stewardship of resource production satisfactory" },
                { "1174", "how can i assist you" },
                { "1175", "yes" },
                { "1176", "i'm ready" },
                { "1180", "r2 has a message concerning an uprising on a planetary system" },
                { "1181", "r2 has an important message concerning the status of a planetary system" },
                { "1183", "there is a message from one of our units indicating it has arrived at its destination" },
                { "1184", "r2 has a message indicating that one of our fighter squadrons has replaced its losses and is now at its full strength" },
                { "1186", "there is a message from one of our fleets indicating it has dropped out of hyperspace and has arrived at its destination" },
                { "1187", "r2 has a message indicating that one of our ships has completed all repairs and is now fully operational" },
                { "1188", "a message has been received indicating our fleet has initiated a blockage of an enemy system" },
                { "1189", "oh dear, r2 has a message from one of our planetary systems indicating that the empire is blockading the planet" },
                { "1191", "r2 has a message from one of our planetary systems indicating that a prisonner has escaped" },
                { "1195", "r2 has a message from one of our field personnel" },
                { "1201", "i'm afraid i do not understand that order" },
                { "1202", "i'm not sure i know how to do that" },
                { "1203", "i'm sorry but you can't move a facility once it has been deployed" },
                { "1204", "i have some advice that may be of some assistance" },
                { "1205", "" },
                { "1206", "" },
                { "1207", "" },
                { "1208", "" },
                { "1209", "" },
                { "1210", "" },
                { "1211", "" },
                { "1212", "" },
                { "1213", "" },
                { "1214", "" },
                { "1215", "" },
                { "1219", "" },
                { "1291", "" },
                { "1292", "" },
                { "1293", "" },
                { "1294", "" },
                { "1295", "" },
                { "1296", "" },
                { "1301", "" },
                { "1302", "" },
                { "1303", "" },
                { "1304", "" },
                { "1305", "" },
                { "1306", "" },
                { "1307", "" },
                { "1308", "" },
                { "1309", "" },
                { "1310", "" },
                { "1311", "" },
                { "1312", "" },
                { "1313", "" },
                { "1314", "" },
                { "1315", "" },
                { "1316", "" },
                { "1317", "" },
                { "1318", "" },
                { "1319", "" },
                { "1320", "" },
                { "1321", "" },
                { "1322", "" },
                { "1323", "" },
                { "1324", "" },
                { "1325", "" },
                { "1326", "" },
                { "1327", "" },
                { "1328", "" },
                { "1329", "" },
                { "1330", "" },
                { "1331", "" },
                { "1332", "" },
                { "1333", "" },
                { "1334", "" },
                { "1335", "" },
                { "1336", "" },
                { "1337", "" },
                { "1338", "" },
                { "1339", "" },
                { "1340", "" },
                { "1341", "" },
                { "1342", "" },
                { "1343", "" },
                { "1344", "" },
                { "1345", "" },
                { "1346", "" },
                { "1347", "" },
                { "1348", "" },
                { "1349", "" },
                { "1350", "" },
                { "1351", "" },
                { "1352", "" },
                { "1353", "" },
                { "1354", "" },
                { "1355", "" },
                { "1356", "" },
                { "1357", "" },
                { "1358", "" },
                { "1359", "" },
                { "1360", "" },
                { "1361", "" },
                { "1362", "" },
                { "1363", "" },
                { "1364", "" },
                { "1365", "" },
                { "1366", "" },
                { "1367", "" },
                { "1368", "" },
                { "1369", "" },
                { "1370", "" },
                { "1371", "" },
                { "1372", "" },
                { "1373", "" },
                { "1374", "" },
                { "1375", "" },
                { "1376", "" },
                { "1377", "" },
                { "1378", "" },
                { "1379", "" },
                { "1380", "" },
                { "1381", "" },
                { "1382", "" },
                { "1383", "" },
                { "1384", "" },
                { "1385", "" },
                { "1386", "" },
                { "1387", "" },
                { "1388", "" },
                { "1389", "" },
                { "1390", "" },
                { "1391", "" },
                { "1392", "" },
                { "1393", "" },
                { "1394", "" },
                { "1395", "" },
                { "1397", "" },
                { "1398", "" },
                { "1399", "" },
                { "1400", "" },
                { "1401", "" },
                { "1402", "" },
                { "1403", "" },
                { "1404", "" },
                { "1405", "" },
                { "1406", "" },
                { "1407", "" },
                { "1408", "" },
                { "1501", "" },
                { "1502", "" },
                { "1503", "" },
                { "1504", "" },
                { "1505", "" },
                { "1506", "" },
                { "1507", "" },
                { "1508", "" },
                { "1509", "" },
                { "1512", "" },
                { "1514", "" },
                { "1515", "" },
                { "1516", "" },
                { "1517", "" },
                { "1519", "" },
                { "1521", "" },
                { "1522", "" },
                { "1523", "" },
                { "1524", "" },
                { "1528", "" },
                { "1529", "" },
                { "1531", "" },
            };
    }
}
