namespace SwRebellionEditor;

// WAVE, Bitmap, RCData, Version Info, 302

public class Alsprite : ResourcesDll
{
    public Alsprite(string fileName) : base(fileName)
    {
        NamesBitmap = new Dictionary<string, string>
            {
                { "2001" , "c3p0-anim 01" },
                { "2041" , "c3p0-anim 02" },
                { "2301" , "c3p0-anim 03" },
                { "2401" , "c3p0-anim 04" },
                { "2511" , "c3p0-anim 05" },
                { "2551" , "c3p0-anim 06" },
                { "2651" , "c3p0-anim 07" },
                { "2751" , "c3p0-anim 08" },
                { "2901" , "c3p0-anim 09" },
                { "2941" , "c3p0-anim 10" },
                { "3002" , "c3p0-anim 11" },
                { "3100" , "c3p0-anim 12" },
                { "3331" , "r2d2-anim 01" },
                { "3370" , "r2d2-anim 02" },
                { "3400" , "c3p0-anim 01" },
                { "3460" , "c3p0-anim 02" },
                { "3511" , "c3p0-anim 03" },
                { "3531" , "c3p0-anim 04" },
                { "3770" , "c3p0-anim 05" },
                { "3800" , "c3p0-anim 06" },
                { "3900" , "c3p0-anim 07" },
                { "16000", "c3p0-anim 08" },
                { "16100", "c3p0-anim 09" },
                { "16150", "c3p0-anim 10" },
                { "16200", "c3p0-anim 11" },
                { "16250", "c3p0-anim 12" },
                { "16300", "c3p0-anim 13" },
                { "16350", "c3p0-anim 14" },
                { "16400", "c3p0-anim 14" },
                { "16450", "c3p0-anim 15" },
                { "16500", "c3p0-anim 16" },
                { "16600", "c3p0-anim 17" },
                { "19600", "c3p0-anim 18" },
                { "19610", "c3p0-anim 19" },
                { "19630", "c3p0-anim 20" },
                { "19650", "c3p0-anim 21" },
                { "19670", "c3p0-anim 22" },
                { "19690", "c3p0-anim 23" },
            };
        NamesWave = new Dictionary<string, string>
            {
                { "1017", "c3po-well, if you'll not be needing me, i'll close down for a while" },
                { "1018", "c3po-oh, ah, ah, yes, i am here" },
                { "1056", "c3po-oh dear, captain solo has been captured" },
                { "1058", "c3po-princess leia has been capture, oh my" },
                { "1078", "c3po-a capture of darth vader is excellent news" },
                { "1079", "c3po-we've captured the emperor, this is certainly good news" },
                { "1080", "c3po-oh no, darth vader has escaped" },
                { "1081", "c3po-the emperor has escaped, we're doomed" },
                { "1084", "c3po-oh dear, president mon mothma has been captured by the empire, we must rescue the president" },
                { "1085", "c3po-oh no, master luke has been captured, we've got to find him and send a rescue mission" },
                { "1086", "c3po-president mon mothma is free of the empire" },
                { "1087", "c3po-luke skywalker has escaped, i never doubted he would" },
                { "1093", "c3po-imperial ships" },
                { "1094", "c3po-the empire is defeated, we've done it" },
                { "1096", "c3po-may i remind you that no messages may be sent to units in hyperspace, i'm afraid you'll have to wait until those units arrive at their destination" },
                { "1097", "c3po-units can only be deployed to a system we control" },
                { "1098", "c3po-there are units assigned to the mission which are not capable of acting on the assigned target, i'm afraid no mission could be formed" },
                { "1099", "c3po-personnel cannot be assigned to missions with reconnaissance units" },
                { "1100", "c3po-damage to one or more ships in the fleet, prevents them from entering hyperspace" },
                { "1101", "c3po-that system has been destroyed by the empire, we can't send anyone there" },
                { "1102", "c3po-excuse me, but that ship class is not capable of carrying those type of units" },
                { "1103", "c3po-i'm sorry, unfortunately, that fleet does not have sufficient capacity to hold all of those units" },
                { "1104", "c3po-i'm sorry, unfortunately, that fleet is filled to capacity, i'm afraid your order cannot be carried out" },
                { "1105", "c3po-i'm sorry, your order to build that new unit cannot be carried out, we don't have the maintenance capacity to support it" },
                { "1106", "c3po-i'm afraid there is not enough energy available in that system, you must have free energy for each new facility" },
                { "1107", "c3po-i'm afraid but there are not enough raw materials, you must have untapped raw materials for each new mine" },
                { "1108", "c3po-i'm afraid there is not enough energy available in that system to deploy another facility there" },
                { "1109", "c3po-i'm sorry, there are no more raw materials available for exploitation on that system" },
                { "1110", "c3po-might i enquire, what is going on" },
                { "1111", "c3po-sometimes i just don't understand human behavior" },
                { "1113", "c3po-there are messages waiting, r2 is holding them for you" },
                { "1114", "c3po-r2 says there's a message coming in from a planetary system" },
                { "1115", "c3po-r2 indicates that a manufacturing message has been received" },
                { "1116", "c3po-there is a message from maintenance that requires your immediate attention" },
                { "1117", "c3po-r2 says that research and development is transmitting a message" },
                { "1118", "c3po-r2 has good news from support for the alliance" },
                { "1119", "c3po-i'm afraid r2 has some bad news about support for the alliance" },
                { "1124", "c3po-r2 says one of our agents is reporting in" },
                { "1126", "c3po-there is a message from the president" },
                { "1127", "c3po-there is a message from princess leia" },
                { "1128", "c3po-there is a message from master luke" },
                { "1129", "c3po-there is a message from captain solo" },
                { "1131", "c3po-i am fluent in 6 millions forms of communication, this signal is not used by the alliance, it could be an imperial code" },
                { "1132", "c3po-certainly" },
                { "1133", "c3po-i'm afraid we do not have the appropriate manufacturing facilities available" },
                { "1137", "c3po-you want me to supervise our planetary garrisons" },
                { "1138", "c3po-i'll be happy to relinquish control of our planetary garrisons to you" },
                { "1139", "c3po-i shall attempt to maximize the output of our mines and refineries" },
                { "1140", "c3po-i hope you found my stewardship of resource production satisfactory" },
                { "1174", "c3po-how can i assist you" },
                { "1175", "c3po-yes" },
                { "1176", "c3po-i'm ready" },
                { "1180", "c3po-r2 has a message concerning an uprising on a planetary system" },
                { "1181", "c3po-r2 has an important message concerning the status of a planetary system" },
                { "1183", "c3po-there is a message from one of our units indicating it has arrived at its destination" },
                { "1184", "c3po-r2 has a message indicating that one of our fighter squadrons has replaced its losses and is now at its full strength" },
                { "1186", "c3po-there is a message from one of our fleets indicating it has dropped out of hyperspace and has arrived at its destination" },
                { "1187", "c3po-r2 has a message indicating that one of our ships has completed all repairs and is now fully operational" },
                { "1188", "c3po-a message has been received indicating our fleet has initiated a blockage of an enemy system" },
                { "1189", "c3po-oh dear, r2 has a message from one of our planetary systems indicating that the empire is blockading the planet" },
                { "1191", "c3po-r2 has a message from one of our planetary systems indicating that a prisonner has escaped" },
                { "1195", "c3po-r2 has a message from one of our field personnel" },
                { "1201", "c3po-i'm afraid i do not understand that order" },
                { "1202", "c3po-i'm not sure i know how to do that" },
                { "1203", "c3po-i'm sorry but you can't move a facility once it has been deployed" },
                { "1204", "c3po-i have some advice that may be of some assistance" },
                { "1205", "c3po-i have a suggestion that may be helpful" },
                { "1206", "c3po-please consult the advice i have prepared for you" },
                { "1207", "c3po-i think we better do something" },
                { "1208", "c3po-if we are ever going to defeat the empire, we must take action soon" },
                { "1209", "c3po-oh no, the imperial fleet is on its way to our headquarters" },
                { "1210", "c3po-the empire is bombarding one of our planets, you must help them" },
                { "1211", "c3po-oh my, imperial troops are assaulting one of our planets" },
                { "1212", "c3po-i'm sorry, but missions can not be assigned to decoys alone" },
                { "1213", "c3po-i'm sorry, but the empire has blockaded that system" },
                { "1214", "c3po-i'm afraid that unit is still under construction" },
                { "1215", "c3po-i'm sorry, but you can not move those units to the selected target" },
                { "1219", "c3po-begging your pardon, i have a suggestion for you" },
				
                { "1291", "blank-scott witte sound forge 4.0" },
                { "1292", "blank-scott witte sound forge 4.0" },
                { "1293", "blank-scott witte sound forge 4.0" },
                { "1294", "blank-scott witte sound forge 4.0" },
                { "1295", "blank-scott witte sound forge 4.0" },
                { "1296", "blank-scott witte sound forge 4.0" },

                { "1301", "luke-i'm on my way" },
                { "1302", "luke-right away" },
                { "1303", "luke-you got it" },
                { "1304", "luke-we did it" },
                { "1305", "luke-we showed them" },
                { "1306", "luke-our mission was successful" },
                { "1307", "luke-blast" },
                { "1308", "luke-that didn't go very well" },
                { "1309", "luke-i've got a bad feeling about this" },
                { "1310", "luke-but I was going in to Tashi station to pick up some power converters" },
                { "1311", "luke-i've arrived" },
                { "1312", "luke-all set" },
                { "1313", "luke-we're on our way back" },
                { "1314", "luke-what's wrong" },
                { "1315", "luke-i've escaped" },
                { "1316", "luke-i've slipped away from the empire" },
                { "1317", "luke-i feel like i could take on the whole empire myself" },
                { "1318", "luke-i've got to help han" },
                { "1319", "luke-something is not right here, i sense something" },
                { "1320", "luke-i can feel the force" },
                { "1321", "luke-someone has betrayed our mission to the empire" },
                { "1322", "luke-i've arrived" },
                { "1323", "luke-i'm ready for duty" },
                { "1324", "luke-mission aborted, i'm returning to base" },
                { "1325", "luke-i'm free of the empire" },
                { "1326", "luke-i feel great" },
                { "1327", "luke-i'm on my way to rescue han" },
                { "1328", "luke-there is a disturbance in the force" },
                { "1329", "luke-i am growing stronger with the force" },
                { "1330", "luke-the force has revealed a traitor in our midst" },
                { "1331", "luke-i have found a new jedi candidate" },
                { "1332", "luke-my jedi training session is completed" },

                { "1333", "leia-i hope you know what you are doing" },
                { "1334", "leia-i'm on my way" },
                { "1335", "leia-we did it" },
                { "1336", "leia-we need to keep this up" },
                { "1337", "leia-we've got to do better" },
                { "1338", "leia-that was a mess" },
                { "1339", "leia-i have a bad feeling about this" },
                { "1340", "leia-i don't know who you are or where you came from, but from now on you do as i tell you, ok" },
                { "1341", "leia-this is some rescue" },
                { "1342", "leia-put that thing away, you're gonna get us all killed" },
                { "1343", "leia-it's a wonder you're still alive" },
                { "1344", "leia-i've arrived" },
                { "1345", "leia-we've aborted the mission" },
                { "1346", "leia-i'm free of my captors" },
                { "1347", "leia-i'm ready" },
                { "1348", "leia-we've got to save han" },
                { "1349", "leia-luke has revealed to me that I can use the force as well" },
                { "1350", "leia-my control of the force is improving" },
                { "1351", "leia-i sense a presence" },
                { "1352", "leia-someone has betrayed our mission to the empire" },

                { "1353", "solo-you got it" },
                { "1354", "solo-i told you it was gonna work" },
                { "1355", "solo-no problem" },
                { "1356", "solo-our mission was successful" },
                { "1357", "solo-sometimes i amaze even myself" },
                { "1358", "solo-it's not my fault" },
                { "1359", "solo-that was just great" },
                { "1360", "solo-i got a bad feeling about this" },
                { "1361", "solo-i'm here" },
                { "1362", "solo-ok, now what" },
                { "1363", "solo-hey i had everything under control, what's the problem" },
                { "1364", "solo-it's about time you pulled us out of there" },
                { "1365", "solo-not bad, huh" },
                { "1366", "solo-i'm feeling great" },
                { "1367", "solo-these guys just don't know when to quit" },

                { "1368", "mon mothma-understood" },
                { "1369", "mon mothma-our goal has been achieved" },
                { "1370", "mon mothma-the empire has bested us" },
                { "1371", "mon mothma-i've got a bad feeling about this" },
                { "1372", "mon mothma-i've arrived" },
                { "1373", "mon mothma-we've aborted the mission" },
                { "1374", "mon mothma-i'm free of the empire" },
                { "1375", "mon mothma-i'm ready to serve the alliance" },

                { "1376", "vader-as you wish" },
                { "1377", "vader-i have succeded" },
                { "1378", "vader-my mission has failed" },
                { "1379", "vader-i have arrived" },
                { "1380", "vader-you have aborted my mission" },
                { "1381", "vader-the rebels can not hold me" },
                { "1382", "vader-i have healed myself with the power of the force" },
                { "1383", "vader-there is a tremor in the force" },
                { "1384", "vader-i have uncovered a rebel spy" },

                { "1385", "palpatine-as you wish" },
                { "1386", "palpatine-i have been successful" },
                { "1387", "palpatine-you have not adequately supported me on this mission and it has failed" },
                { "1388", "palpatine-i have arrived" },
                { "1389", "palpatine-why have you not allowed me to finish the mission" },
                { "1390", "palpatine-the foolish Rebels can not hope to hold me" },
                { "1391", "palpatine-i am whole again by the use of the force" },
                { "1392", "palpatine-i have felt a presence" },
                { "1393", "palpatine-i have detected a rebel spy" },
                { "1394", "palpatine-i have returned to my throne" },

                { "1395", "luke-how am i to know the good side from the bad-yoda-you will know. a jedi uses the force for knowledge or defense, never for attack" },
                { "1397", "vader-join me, and together we can rule the galaxy as father and son-luke-i'll never join you" },
                { "1398", "solo-look jabba i was on my way to pay you back and i got a little sidetracked, it's not my fault-jabba-blablabla" },
				{ "1399", "vader-the force is with you, young skywalker, but you are not a jedi yet-luke-you'll find i'm stronger than you think" },
                { "1400", "palpatine-your feeble skills are no match for me-luke-you'll find i'm full of surprises" },
                { "1401", "vader-obi-wan has taught you well-luke-i do not wish to fight you father" },
    			{ "1402", "palpatine-welcome young skywalker, i have been expecting you-luke-you have been the cause of all this" },
				{ "1403", "luke-you failed your highness, i am a jedi like my father before me-palpatine-you'll pay the price for your lack of vision" },
				{ "1404", "palpatine-you, like your father, are now mine-vader-give yourself to the dark side-luke-i'll never turn to the dark side" },
                { "1405", "vader-well your highness, we meet again-leia-this galaxy would be a better place without you" },
				{ "1406", "palpatine-it's time for you to join the rest of your people-leia-you'll pay for what you've done to my people" },
                { "1407", "solo-i have a bad feeling about this-chewbacca-blablabla-fett-i have done your bidding-vader-the empire will reward your service" },
                { "1408", "solo-together again-luke-i wouldnt miss it-fett-i have done your bidding-vader-the empire will reward your service" },

                { "1501", "r2d2-strategic event noises 01" },
                { "1502", "r2d2-strategic event noises 02" },
                { "1503", "r2d2-strategic event noises 03" },
                { "1504", "r2d2-strategic event noises 04" },
                { "1505", "r2d2-strategic event noises 05" },
                { "1506", "r2d2-strategic event noises 06" },
                { "1507", "r2d2-strategic event noises 07" },
                { "1508", "r2d2-strategic event noises 08" },
                { "1509", "r2d2-strategic event noises 09" },
                { "1512", "r2d2-strategic event noises 10" },
                { "1514", "r2d2-strategic event noises 11" },
                { "1515", "r2d2-strategic event noises 12" },
                { "1516", "r2d2-strategic event noises 13" },
                { "1517", "r2d2-strategic event noises 14" },
                { "1519", "r2d2-strategic event noises 15" },
                { "1521", "r2d2-strategic event noises 16" },
                { "1522", "r2d2-strategic event noises 17" },
                { "1523", "r2d2-strategic event noises 18" },
                { "1524", "r2d2-strategic event noises 19" },
                { "1528", "r2d2-strategic event noises 20" },
                { "1529", "r2d2-strategic event noises 21" },
                { "1531", "r2d2-strategic event noises 22" },
            };
    }
}
