namespace SwRebellionEditor;

// WAVE, Bitmap, RCData, Version Info, 302

public class Emsprite : ResourcesDll
{
    public Emsprite(string fileName) : base(fileName)
    {
        NamesBitmap = new Dictionary<string, string>
            {
                { "2001" , "droid-anim 01" },
                { "2100" , "droid-anim 02" },
                { "2300" , "droid-anim 03" },
                { "2380" , "droid-anim 04" },
                { "2432" , "droid-anim 05" },
                { "2525" , "droid-anim 06" },
                { "2642" , "droid-anim 07" },
                { "3001" , "sd7" },
                { "6000" , "droid-anim 01" },
                { "6100" , "droid-anim 02" },
                { "6200" , "droid-anim 03" },
                { "6300" , "droid-anim 04" },
                { "6400" , "droid-anim 05" },
                { "6500" , "droid-anim 06" },
                { "6600" , "droid-anim 07" },
                { "6800" , "droid-anim 08" },
                { "7000" , "droid-anim 09" },
                { "7100" , "droid-anim 10" },
                { "7200" , "droid-anim 11" },
                { "7300" , "droid-anim 12" },
                { "7500" , "droid-anim 13" },
                { "7600" , "droid-anim 14" },
                { "7700" , "droid-anim 15" },
                { "7800" , "droid-anim 16" },
                { "8100" , "droid-anim 17" },
                { "8200" , "droid-anim 18" },
                { "8300" , "droid-anim 19" },
                { "8500" , "droid-anim 20" },
                { "8700" , "droid-anim 21" },
                { "8716" , "droid-anim 22" },
                { "8732" , "droid-anim 23" },
                { "8750" , "droid-anim 24" },
                { "8770" , "droid-anim 25" },
                { "8790" , "droid-anim 26" },
            };
        NamesWave = new Dictionary<string, string>
            {
                { "1100" , "droid-damage to one or more ships in that fleet prevents them from entering hyperspace" },
                { "1101" , "droid-if you recall, you ordered that system destroyed. no units can be sent to that location" },
                { "1102" , "droid-the assigned ship class is not capable of carrying those types of units" },
                { "1103" , "droid-the fleet does not have sufficient capacity to hold all of those units" },
                { "1104" , "droid-the assigned fleet is filled to capacity, your order can not be carried out" },
                { "1105" , "droid-your order to build that new unit can not be carried out, we do not have sufficient maintenance capacity to support it" },
                { "1106" , "droid-gravitational effects make it impossible for 2 death stars to be located in the same system, your order could not be carried out" },
                { "1107" , "droid-your order can not be carried out, you must have a new system energy for each new facility" },
                { "1108" , "droid-your order can not be carried out, you must have untapped raw materials for each new mine" },
                { "1109" , "droid-your order can not be carried out, there is not enough energy available in that system to deploy another facility there" },
                { "1110" , "droid-your order can not be carried out, there are no more raw materials available for exploitation on that system" },
                { "1111" , "droid-you seem to be having some difficulty with the concept" },
                { "1112" , "droid-mmm, perhaps there has been some mistake" },
                { "1113" , "droid-there are messages waiting, sd7 is holding them for you" },
                { "1114" , "droid-there is a message coming in from a planetary system" },
                { "1115" , "droid-a manufacturing message has been received" },
                { "1116" , "droid-a message from maintenance has been received" },
                { "1117" , "droid-research and development is transmitting a message" },
                { "1118" , "droid-there is a message concerning popular support for the empire" },
                { "1119" , "droid-there appears to be some negative news about support for the empire" },
                { "1124" , "droid-one of our agents is reporting in" },
                { "1126" , "droid-there is a message from lord vader" },
                { "1127" , "droid-there is a message from The emperor" },
                { "1129" , "droid-it would seem the alliance is attempting to contact you" },
                { "1130" , "droid-as you command" },
                { "1131" , "droid-we do not seem to have the appropriate manufacturing facilities available to execute your order" },
                { "1135" , "droid-i am most willing to supervise our planetary garrisons" },
                { "1136" , "droid-relinquishing control of our planetary garrisons to you" },
                { "1137" , "droid-your humble servant will maximize the output of all imperial mines and refineries" },
                { "1138" , "droid-i yield control of resource production to you" },
                { "1167" , "droid-what do you desire" },
                { "1168" , "droid-yes" },
                { "1169" , "droid-droid laughters" },
                { "1171" , "droid-there is some information about an uprising on a planetary system" },
                { "1172" , "droid-there has been a change in the status of a planetary system" },
                { "1174" , "droid-there is a message from an imperial unit, indicating it has arrived at its destination" },
                { "1175" , "droid-it appears that an imperial fighter squadron has replaced its losses and is now at full strength" },
                { "1177" , "droid-there is a message from an imperial fleet indicating it has reached its destination" },
                { "1178" , "droid-there is a message indicating that an imperial ship has completed all repairs and is now fully operational" },
                { "1179" , "droid-a message has been received indicating the imperial fleet has initiated a blockade of an enemy system" },
                { "1180" , "droid-it appears that the alliance is blockading one of the empire's planets" },
                { "1182" , "droid-apparantly there is a message indicating that a prisoner has escaped" },
                { "1185" , "droid-there is a message from one of your field personnel" },
                { "1201" , "droid-that last order was a bit unclear" },
                { "1202" , "droid-just what do you think you are doing" },
                { "1203" , "droid-you can't move a facility once it has been deployed" },
                { "1204" , "droid-may i offer some advice" },
                { "1205" , "droid-might i offer a suggestion" },
                { "1206" , "droid-i have some advice that would be helpful" },
                { "1207" , "droid-the galaxy is not going to conquer itself you know" },
                { "1208" , "droid-the emperor is not going to be pleased with your lack of action" },
                { "1209" , "droid-we have new information about captain solo" },
                { "1210" , "droid-the rebels are bombarding one of our planets, perhaps you should do something about this" },
                { "1211" , "droid-rebel troops are invading one of our planets" },
                { "1212" , "droid-missions can not be assigned to decoys alone" },
                { "1213" , "droid-i'm afraid that system is currently blockaded by the rebels" },
                { "1214" , "droid-that unit is still under construction" },
                { "1215" , "droid-it is not possible for you to move those units to the selected target" },
                { "1219" , "droid-you might do well to heed my advice" },

                { "1301" , "luke-i'm on my way" },
                { "1302" , "luke-right away" },
                { "1303" , "luke-you got it" },
                { "1304" , "luke-we did it" },
                { "1305" , "luke-we showed them" },
                { "1306" , "luke-our mission was successful" },
                { "1307" , "luke-blast" },
                { "1308" , "luke-that didn't go very well" },
                { "1309" , "luke-i've got a bad feeling about this" },
                { "1310" , "luke-but I was going in to Tashi station to pick up some power converters" },
                { "1311" , "luke-i've arrived" },
                { "1312" , "luke-all set" },
                { "1313" , "luke-we're on our way back" },
                { "1314" , "luke-what's wrong" },
                { "1315" , "luke-i've escaped" },
                { "1316" , "luke-i've slipped away from the empire" },
                { "1317" , "luke-i feel like i could take on the whole empire myself" },
                { "1318" , "luke-i've got to help han" },
                { "1319" , "luke-something is not right here, i sense something" },
                { "1320" , "luke-i can feel the force" },
                { "1321" , "luke-someone has betrayed our mission to the empire" },
                { "1322" , "luke-i've arrived" },
                { "1323" , "luke-i'm ready for duty" },
                { "1324" , "luke-mission aborted, i'm returning to base" },
                { "1325" , "luke-i'm free of the empire" },
                { "1326" , "luke-i feel great" },
                { "1327" , "luke-i'm on my way to rescue han" },
                { "1328" , "luke-there is a disturbance in the force" },
                { "1329" , "luke-i am growing stronger with the force" },
                { "1330" , "luke-the force has revealed a traitor in our midst" },
                { "1331" , "luke-i have found a new jedi candidate" },
                { "1332" , "luke-my jedi training session is completed" },

                { "1333" , "leia-i hope you know what you are doing" },
                { "1334" , "leia-i'm on my way" },
                { "1335" , "leia-we did it" },
                { "1336" , "leia-we need to keep this up" },
                { "1337" , "leia-we've got to do better" },
                { "1338" , "leia-that was a mess" },
                { "1339" , "leia-i have a bad feeling about this" },
                { "1340" , "leia-i don't know who you are or where you came from, but from now on you do as i tell you, ok" },
                { "1341" , "leia-this is some rescue" },
                { "1342" , "leia-put that thing away, you're gonna get us all killed" },
                { "1343" , "leia-it's a wonder you're still alive" },
                { "1344" , "leia-i've arrived" },
                { "1345" , "leia-we've aborted the mission" },
                { "1346" , "leia-i'm free of my captors" },
                { "1347" , "leia-i'm ready" },
                { "1348" , "leia-we've got to save han" },
                { "1349" , "leia-luke has revealed to me that I can use the force as well" },
                { "1350" , "leia-my control of the force is improving" },
                { "1351" , "leia-i sense a presence" },
                { "1352" , "leia-someone has betrayed our mission to the empire" },
                         
                { "1353" , "solo-you got it" },
                { "1354" , "solo-i told you it was gonna work" },
                { "1355" , "solo-no problem" },
                { "1356" , "solo-our mission was successful" },
                { "1357" , "solo-sometimes i amaze even myself" },
                { "1358" , "solo-it's not my fault" },
                { "1359" , "solo-that was just great" },
                { "1360" , "solo-i got a bad feeling about this" },
                { "1361" , "solo-i'm here" },
                { "1362" , "solo-ok, now what" },
                { "1363" , "solo-hey i had everything under control, what's the problem" },
                { "1364" , "solo-it's about time you pulled us out of there" },
                { "1365" , "solo-not bad, huh" },
                { "1366" , "solo-i'm feeling great" },
                { "1367" , "solo-these guys just don't know when to quit" },
                         
                { "1368" , "mon mothma-understood" },
                { "1369" , "mon mothma-our goal has been achieved" },
                { "1370" , "mon mothma-the empire has bested us" },
                { "1371" , "mon mothma-i've got a bad feeling about this" },
                { "1372" , "mon mothma-i've arrived" },
                { "1373" , "mon mothma-we've aborted the mission" },
                { "1374" , "mon mothma-i'm free of the empire" },
                { "1375" , "mon mothma-i'm ready to serve the alliance" },
                         
                { "1376" , "vader-as you wish" },
                { "1377" , "vader-i have succeded" },
                { "1378" , "vader-my mission has failed" },
                { "1379" , "vader-i have arrived" },
                { "1380" , "vader-you have aborted my mission" },
                { "1381" , "vader-the rebels can not hold me" },
                { "1382" , "vader-i have healed myself with the power of the force" },
                { "1383" , "vader-there is a tremor in the force" },
                { "1384" , "vader-i have uncovered a rebel spy" },
                         
                { "1385" , "palpatine-as you wish" },
                { "1386" , "palpatine-i have been successful" },
                { "1387" , "palpatine-you have not adequately supported me on this mission and it has failed" },
                { "1388" , "palpatine-i have arrived" },
                { "1389" , "palpatine-why have you not allowed me to finish the mission" },
                { "1390" , "palpatine-the foolish Rebels can not hope to hold me" },
                { "1391" , "palpatine-i am whole again by the use of the force" },
                { "1392" , "palpatine-i have felt a presence" },
                { "1393" , "palpatine-i have detected a rebel spy" },
                { "1394" , "palpatine-i have returned to my throne" },
                         
                { "1395" , "luke-how am i to know the good side from the bad-yoda-you will know. a jedi uses the force for knowledge or defense, never for attack" },
                { "1397" , "vader-join me, and together we can rule the galaxy as father and son-luke-i'll never join you" },
                { "1398" , "solo-look jabba i was on my way to pay you back and i got a little sidetracked, it's not my fault-jabba-blablabla" },
                { "1399" , "vader-the force is with you, young skywalker, but you are not a jedi yet-luke-you'll find i'm stronger than you think" },
                { "1400" , "palpatine-your feeble skills are no match for me-luke-you'll find i'm full of surprises" },
                { "1401" , "vader-obi-wan has taught you well-luke-i do not wish to fight you father" },
                { "1402" , "palpatine-welcome young skywalker, i have been expecting you-luke-you have been the cause of all this" },
                { "1403" , "luke-you failed your highness, i am a jedi like my father before me-palpatine-you'll pay the price for your lack of vision" },
                { "1404" , "palpatine-you, like your father, are now mine-vader-give yourself to the dark side-luke-i'll never turn to the dark side" },
                { "1405" , "vader-well your highness, we meet again-leia-this galaxy would be a better place without you" },
                { "1406" , "palpatine-it's time for you to join the rest of your people-leia-you'll pay for what you've done to my people" },
                { "1407" , "solo-i have a bad feeling about this-chewbacca-blablabla-fett-i have done your bidding-vader-the empire will reward your service" },
                { "1408" , "solo-together again-luke-i wouldnt miss it-fett-i have done your bidding-vader-the empire will reward your service" },

                { "1517" , "droid-as you wish" },
                { "1518" , "droid-i am ready to serve, as always" },
                { "1556" , "droid-ah, the rebel agent captain solo has been captured, excellent" },
                { "1558" , "droid-excellent, the rebel leader, princess leia organa, has been captured" },
                { "1578" , "droid-the capture of mon mothma is a severe blow to the rebels" },
                { "1579" , "droid-so skywalker has been abducted, the emperor will be most pleased" },
                { "1581" , "droid-luke skywalker has escaped, the emperor will be most displeased" },
                { "1582" , "droid-the rebels have foolishly attempted to capture lord vader, of course i'm sure you will make every to ensure his security" },
                { "1584" , "droid-you have allowed lord vader to be captured, i think this is going to look bad on your record" },
                { "1585" , "droid-you have failed in your responsibilities, the emperor has been captured by the rebels, i'm sure your duty is clear" },
                { "1586" , "droid-how fortunate for you, lord vader has escaped the rebels" },
                { "1587" , "droid-the emperor has escaped from the rebels, perhaps the Emperor is in a forgiving mood" },
                { "1593" , "droid-your failure is now complete" },
                { "1594" , "droid-you have served the empire well, the emperor will surely reward victory" },
                { "1596" , "droid-units in hyperspace are unable to receive commands, you can issue orders to those units when they arrive at their destination" },
                { "1597" , "droid-those units can only be deployed to a system under your control" },
                { "1598" , "droid-you have assigned units to the mission which are not capable of acting upon the assigned target, no mission could be performed" },
                { "1599" , "droid-personnel can not be assigned to missions with reconnaissance units" },
				
                { "1801" , "sd7-strategic event noises 01" },
                { "1802" , "sd7-strategic event noises 02" },
                { "1803" , "sd7-strategic event noises 03" },
                { "1804" , "sd7-strategic event noises 04" },
                { "1805" , "sd7-strategic event noises 05" },
                { "1806" , "sd7-strategic event noises 06" },
                { "1807" , "sd7-strategic event noises 07" },
                { "1808" , "sd7-strategic event noises 08" },
                { "1810" , "sd7-strategic event noises 09" },
                { "1812" , "sd7-strategic event noises 10" },
                { "1814" , "sd7-strategic event noises 11" },
                { "1815" , "sd7-strategic event noises 12" },
                { "1817" , "sd7-strategic event noises 13" },
                { "1819" , "sd7-strategic event noises 14" },
                { "1820" , "sd7-strategic event noises 15" },
                { "1822" , "sd7-strategic event noises 16" },
                { "1823" , "sd7-strategic event noises 17" },
                { "1826" , "sd7-strategic event noises 18" },
                { "1827" , "sd7-strategic event noises 19" },
                { "1829" , "sd7-strategic event noises 20" },

                { "22001", "blank-scott witte sound forge 4.0" },
                { "22002", "blank-scott witte sound forge 4.0" },
                { "22003", "blank-scott witte sound forge 4.0" },
                { "22004", "blank-scott witte sound forge 4.0" },
                { "22005", "blank-scott witte sound forge 4.0" },
                { "22006", "blank-scott witte sound forge 4.0" },
                { "23001", "blank-scott witte sound forge 4.0" },
                { "23002", "blank-scott witte sound forge 4.0" },
                { "23003", "blank-scott witte sound forge 4.0" },
                { "23004", "blank-scott witte sound forge 4.0" },
                { "23005", "blank-scott witte sound forge 4.0" },
                { "23006", "blank-scott witte sound forge 4.0" },
            };
    }
}
