namespace SwRebellionEditor;

// Bitmap, Version Info

public class Gokres : ResourcesDll
{
    public Gokres(string fileName) : base(fileName)
    {
        NamesBitmap = new Dictionary<string, string>
            {
                // facilities (status window)
                { "1"    , "status-facility-mine" },
                { "2"    , "status-facility-refinery" },
                { "256"  , "status-facility-orbital-shipyard" },
                { "257"  , "status-facility-training-facility" },
                { "258"  , "status-facility-construction-yard" },
                { "259"  , "status-facility-advanced-shipyard" },
                { "260"  , "status-facility-advanced-training-facility" },
                { "261"  , "status-facility-advanced-construction-yard" },
                // facilities tabs
                { "262"  , "tab-facility-orbital-shipyard" },
                { "263"  , "tab-facility-training-facility" },
                { "264"  , "tab-facility-construction-yard" },
                // facilities (status window)
                { "512"  , "status-facility-kdy-150" },
                { "513"  , "status-facility-lnr-series-1" },
                { "514"  , "status-facility-gencore-level-1" },
                { "515"  , "status-facility-lnr-series-2" },
                { "516"  , "status-facility-gencore-level-2" },
                { "640"  , "status-facility-death-star-shield" },
                { "832"  , "status-facility-alliance-headquarters" },
                // troops (status window)
                { "1088" , "status-troop-alliance-alliance-fleet-regiment" },
                { "1089" , "status-troop-alliance-alliance-army-regiment" },
                { "1090" , "status-troop-alliance-sullustan-regiment" },
                { "1091" , "status-troop-alliance-wookiee-regiment" },
                { "1092" , "status-troop-alliance-mon-calamari-regiment" },
                { "1152" , "status-troop-empire-stormtrooper-regiment" },
                { "1153" , "status-troop-empire-imperial-fleet-regiment" },
                { "1154" , "status-troop-empire-imperial-army-regiment" },
                { "1155" , "status-troop-empire-war-droid-regiment" },
                { "1156" , "status-troop-empire-dark-trooper-regiment" },
                // special forces (status window)
                { "1344" , "status-special-force-alliance-guerillas" },
                { "1345" , "status-special-force-alliance-infiltrators" },
                { "1346" , "status-special-force-alliance-longprobe-y-wing-recon-team" },
                { "1347" , "status-special-force-alliance-bothan-spies" },
                { "1408" , "status-special-force-empire-imperial-probe-droid" },
                { "1409" , "status-special-force-empire-imperial-espionage-droid" },
                { "1410" , "status-special-force-empire-imperial-commandos" },
                { "1411" , "status-special-force-empire-noghri-death-commandos" },
                { "1412" , "status-special-force-empire-bounty-hunters" },
                // fighters (status window)
                { "1600" , "status-fighter-alliance-a-wing" },
                { "1601" , "status-fighter-alliance-b-wing" },
                { "1602" , "status-fighter-alliance-x-wing" },
                { "1603" , "status-fighter-alliance-y-wing" },
                { "1664" , "status-fighter-empire-tie-fighter" },
                { "1665" , "status-fighter-empire-tie-interceptor" },
                { "1666" , "status-fighter-empire-tie-bomber" },
                { "1667" , "status-fighter-empire-tie-defender" },
                // capital ships (status window)
                { "1856" , "status-ship-alliance-mon-calamari-cruiser_mc80-liberty-cruiser" },
                { "1857" , "status-ship-alliance-bulk-cruiser" },
                { "1858" , "status-ship-alliance-assault-frigate" },
                { "1859" , "status-ship-alliance-nebulon-b-frigate" },
                { "1860" , "status-ship-alliance-alliance-escort-carrier" },
                { "1861" , "status-ship-alliance-corellian-corvette" },
                { "1862" , "status-ship-alliance-medium-transport" },
                { "1863" , "status-ship-alliance-bulk-transport_bulk-freighter" },
                { "1864" , "status-ship-alliance-corellian-gunship" },
                { "1865" , "status-ship-alliance-alliance-dreadnaught_mc40a-light-cruiser" },
                { "1866" , "status-ship-alliance-cc-7700-frigate" },
                { "1867" , "status-ship-alliance-bulwark-battlecruiser_viscount-star-defender" },
                { "1868" , "status-ship-alliance-liberator-cruiser" },
                { "1869" , "status-ship-alliance-cc-9600-frigate_mc30c-frigate" },
                { "1870" , "status-ship-alliance-dauntless-cruiser_mc80a-homeone-cruiser" },
                { "1920" , "status-ship-empire-strike-cruiser_vindicator-heavy-cruiser" },
                { "1921" , "status-ship-empire-lancer-frigate" },
                { "1922" , "status-ship-empire-interdictor-cruiser_immobilizer-cruiser" },
                { "1923" , "status-ship-empire-carrack-light-cruiser_arquitens-light-cruiser" },
                { "1924" , "status-ship-empire-victory-destroyer_victory-1-star-destroyer" },
                { "1925" , "status-ship-empire-imperial-star-destroyer_imperial-1-star-destroyer" },
                { "1926" , "status-ship-empire-super-star-destroyer" },
                { "1927" , "status-ship-empire-assault-transport_gladiator-star-destroyer" },
                { "1928" , "status-ship-empire-death-star" },
                { "1929" , "status-ship-empire-galleon_acclamator-drop-ship" },
                { "1930" , "status-ship-empire-victory-2-star-destroyer" },
                { "1931" , "status-ship-empire-imperial-2-star-destroyer" },
                { "1932" , "status-ship-empire-star-galleon_star-galleon-frigate" },
                { "1933" , "status-ship-empire-imperial-escort-carrier" },
                { "1934" , "status-ship-empire-imperial-dreadnaught_imperial-dreadnought" },
                // characters (status window)
                { "2112" , "status-character-alliance-mon-mothma" },
                { "2113" , "status-character-alliance-leia-organa" },
                { "2114" , "status-character-alliance-luke-skywalker" },
                { "2115" , "status-character-alliance-han-solo" },
                { "2128" , "status-character-alliance-luke-knight" },
                { "2176" , "status-character-empire-emperor-palpatine" },
                { "2177" , "status-character-empire-darth-vader" },
                { "2624" , "status-character-alliance-ackbar" },
                { "2625" , "status-character-alliance-wedge-antilles" },
                { "2626" , "status-character-alliance-lando-calrissian" },
                { "2627" , "status-character-alliance-chewbacca" },
                { "2628" , "status-character-alliance-jan-dodonna" },
                { "2629" , "status-character-alliance-crix-madine" },
                { "2630" , "status-character-alliance-carlist-rieekan" },
                { "2631" , "status-character-alliance-afyon" },
                { "2632" , "status-character-alliance-drayson" },
                { "2633" , "status-character-alliance-borsk-fey'lya" },
                { "2634" , "status-character-alliance-tura-raftican" },
                { "2635" , "status-character-alliance-bren-derlin" },
                { "2636" , "status-character-alliance-garm-bel-iblis" },
                { "2637" , "status-character-alliance-talon-karrde" },
                { "2638" , "status-character-alliance-narra" },
                { "2639" , "status-character-alliance-huoba-neva" },
                { "2640" , "status-character-alliance-page" },
                { "2641" , "status-character-alliance-syub-snunb" },
                { "2642" , "status-character-alliance-adar-tallon" },
                { "2643" , "status-character-alliance-sarin-virgilio" },
                { "2644" , "status-character-alliance-vanden-willard" },
                { "2645" , "status-character-alliance-roget-jiriss" },
                { "2646" , "status-character-alliance-kaiya-andrimetrum" },
                { "2647" , "status-character-alliance-mazer-rackus" },
                { "2648" , "status-character-alliance-orrimaarko" },
                { "2649" , "status-character-alliance-ma'w'shiye" },
                { "2688" , "status-character-empire-jerjerrod" },
                { "2689" , "status-character-empire-ozzel" },
                { "2690" , "status-character-empire-piett" },
                { "2691" , "status-character-empire-veers" },
                { "2692" , "status-character-empire-brandei" },
                { "2693" , "status-character-empire-covell" },
                { "2694" , "status-character-empire-dorja" },
                { "2695" , "status-character-empire-bin-essada" },
                { "2696" , "status-character-empire-niles-ferrier" },
                { "2697" , "status-character-empire-grammel" },
                { "2698" , "status-character-empire-griff" },
                { "2699" , "status-character-empire-klev" },
                { "2700" , "status-character-empire-needa" },
                { "2701" , "status-character-empire-bane-nothos" },
                { "2702" , "status-character-empire-orlok" },
                { "2703" , "status-character-empire-pellaeon" },
                { "2704" , "status-character-empire-screed" },
                { "2705" , "status-character-empire-thrawn" },
                { "2706" , "status-character-empire-zuggs" },
                { "2707" , "status-character-empire-daala" },
                { "2708" , "status-character-empire-pter-thanas" },
                { "2709" , "status-character-empire-bevel-lemelisk" },
                { "2710" , "status-character-empire-shenir-rix" },
                { "2711" , "status-character-empire-noval-garaint" },
                { "2712" , "status-character-empire-garindan" },
                { "2713" , "status-character-empire-menndo" },
                { "2714" , "status-character-empire-labansat" },
                { "2715" , "status-character-empire-villar" },
                // missions alliance (status window)
                { "3088" , "status-mission-alliance-diplomacy" },
                { "3089" , "status-mission-alliance-rescue" },
                { "3090" , "status-mission-alliance-sabotage" },
                { "3091" , "status-mission-alliance-espionage" },
                { "3092" , "status-mission-alliance-ship-design-research" },
                { "3093" , "status-mission-alliance-reconnaissance" },
                { "3094" , "status-mission-alliance-recruitment" },
                { "3095" , "status-mission-alliance-abduction" },
                { "3104" , "status-mission-alliance-ship-design-research" },
                { "3105" , "status-mission-alliance-facility-design-research" },
                { "3106" , "status-mission-alliance-troop-training-research" },
                { "3136" , "status-mission-alliance-incite-uprising" },
                { "3137" , "status-mission-alliance-death-star-sabotage" },
                { "3138" , "status-mission-alliance-jedi-training" },
                { "3139" , "status-mission-alliance-jedi-training" },
                { "3140" , "status-mission-alliance-rescue" },
                { "3141" , "status-mission-alliance-jedi-training" },
                { "3142" , "status-mission-alliance-jedi-training" },
                { "3200" , "status-mission-alliance-subdue-uprising" },
                { "3201" , "status-mission-alliance-assassination" },
                { "3202" , "status-mission-alliance-abduction" },
                { "3203" , "status-mission-alliance-abduction" },
                // hyperspace overlays (status window)
                { "5185" , "status-hyperspace-alliance" },
                { "5250" , "status-hyperspace-empire" },
                { "5442" , "status-hyperspace-alliance-longprobe-y-wing-recon-team" },
                { "5504" , "status-hyperspace-empire-imperial-espionage-droid" },
                // reactors for fighters overlays (status window)
                { "5696" , "status-reactors-fighter-alliance-a-wing" },
                { "5697" , "status-reactors-fighter-alliance-b-wing" },
                { "5698" , "status-reactors-fighter-alliance-x-wing" },
                { "5699" , "status-reactors-fighter-alliance-y-wing" },
                { "5760" , "status-reactors-fighter-empire-tie-fighter" },
                { "5761" , "status-reactors-fighter-empire-tie-interceptor" },
                { "5762" , "status-reactors-fighter-empire-tie-bomber" },
                { "5763" , "status-reactors-fighter-empire-tie-defender" },
                // reactors for capital ships overlays
                { "5952" , "status-reactors-ship-alliance-mon-calamari-cruiser_mc80-liberty-cruiser" },
                { "5953" , "status-reactors-ship-alliance-bulk-cruiser" },
                { "5954" , "status-reactors-ship-alliance-assault-frigate" },
                { "5955" , "status-reactors-ship-alliance-nebulon-b-frigate" },
                { "5956" , "status-reactors-ship-alliance-alliance-escort-carrier" },
                { "5957" , "status-reactors-ship-alliance-corellian-corvette" },
                { "5958" , "status-reactors-ship-alliance-medium-transport" },
                { "5959" , "status-reactors-ship-alliance-bulk-transport_bulk-freighter" },
                { "5960" , "status-reactors-ship-alliance-corellian-gunship" },
                { "5961" , "status-reactors-ship-alliance-alliance-dreadnaught_mc40a-light-cruiser" },
                { "5962" , "status-reactors-ship-alliance-cc-7700-frigate" },
                { "5963" , "status-reactors-ship-alliance-bulwark-battlecruiser_viscount-star-defender" },
                { "5964" , "status-reactors-ship-alliance-liberator-cruiser" },
                { "5965" , "status-reactors-ship-alliance-cc-9600-frigate_mc30c-frigate" },
                { "5966" , "status-reactors-ship-alliance-dauntless-cruiser_mc80a-homeone-cruiser" },
                { "6016" , "status-reactors-ship-empire-strike-cruiser_vindicator-heavy-cruiser" },
                { "6017" , "status-reactors-ship-empire-lancer-frigate" },
                { "6018" , "status-reactors-ship-empire-interdictor-cruiser_immobilizer-cruiser" },
                { "6019" , "status-reactors-ship-empire-carrack-light-cruiser_arquitens-light-cruiser" },
                { "6020" , "status-reactors-ship-empire-victory-destroyer_victory-1-star-destroyer" },
                { "6021" , "status-reactors-ship-empire-imperial-star-destroyer_imperial-1-star-destroyer" },
                { "6022" , "status-reactors-ship-empire-super-star-destroyer" },
                { "6023" , "status-reactors-ship-empire-assault-transport_gladiator-star-destroyer" },
                { "6024" , "status-reactors-ship-empire-death-star" },
                { "6025" , "status-reactors-ship-empire-galleon_acclamator-drop-ship" },
                { "6026" , "status-reactors-ship-empire-victory-2-star-destroyer" },
                { "6027" , "status-reactors-ship-empire-imperial-2-star-destroyer" },
                { "6028" , "status-reactors-ship-empire-star-galleon_star-galleon-frigate" },
                { "6029" , "status-reactors-ship-empire-imperial-escort-carrier" },
                { "6030" , "status-reactors-ship-empire-imperial-dreadnaught_imperial-dreadnought" },
                // missions empire (status window)
                { "7184" , "status-mission-empire-diplomacy" },
                { "7185" , "status-mission-empire-rescue" },
                { "7186" , "status-mission-empire-sabotage" },
                { "7187" , "status-mission-empire-espionage" },
                { "7188" , "status-mission-empire-ship-design-research" },
                { "7189" , "status-mission-empire-reconnaissance" },
                { "7190" , "status-mission-empire-recruitment" },
                { "7191" , "status-mission-empire-abduction" },
                { "7200" , "status-mission-empire-ship-design-research" },
                { "7201" , "status-mission-empire-facility-design-research" },
                { "7202" , "status-mission-empire-troop-training-research" },
                { "7232" , "status-mission-empire-incite-uprising" },
                { "7233" , "status-mission-empire-death-star-sabotage" },
                { "7234" , "status-mission-empire-jedi-training" },
                { "7235" , "status-mission-empire-jedi-training" },
                { "7236" , "status-mission-empire-rescue" },
                { "7237" , "status-mission-empire-jedi-training" },
                { "7238" , "status-mission-empire-jedi-training" },
                { "7296" , "status-mission-empire-subdue-uprising" },
                { "7297" , "status-mission-empire-assassination" },
                { "7298" , "status-mission-empire-abduction" },
                { "7299" , "status-mission-empire-abduction" },
                // damage on fighters (status window)
                { "9792" , "status-damage-fighter-alliance-a-wing" },
                { "9793" , "status-damage-fighter-alliance-b-wing" },
                { "9794" , "status-damage-fighter-alliance-x-wing" },
                { "9795" , "status-damage-fighter-alliance-y-wing" },
                { "9856" , "status-damage-fighter-empire-tie-fighter" },
                { "9857" , "status-damage-fighter-empire-tie-interceptor" },
                { "9858" , "status-damage-fighter-empire-tie-bomber" },
                { "9859" , "status-damage-fighter-empire-tie-defender" },
                // damage on capital ships (status window)
                { "10048", "status-damage-ship-alliance-mon-calamari-cruiser_mc80-liberty-cruiser" },
                { "10049", "status-damage-ship-alliance-bulk-cruiser" },
                { "10050", "status-damage-ship-alliance-assault-frigate" },
                { "10051", "status-damage-ship-alliance-nebulon-b-frigate" },
                { "10052", "status-damage-ship-alliance-alliance-escort-carrier" },
                { "10053", "status-damage-ship-alliance-corellian-corvette" },
                { "10054", "status-damage-ship-alliance-medium-transport" },
                { "10055", "status-damage-ship-alliance-bulk-transport_bulk-freighter" },
                { "10056", "status-damage-ship-alliance-corellian-gunship" },
                { "10057", "status-damage-ship-alliance-alliance-dreadnaught_mc40a-light-cruiser" },
                { "10058", "status-damage-ship-alliance-cc-7700-frigate" },
                { "10059", "status-damage-ship-alliance-bulwark-battlecruiser_viscount-star-defender" },
                { "10060", "status-damage-ship-alliance-liberator-cruiser" },
                { "10061", "status-damage-ship-alliance-cc-9600-frigate_mc30c-frigate" },
                { "10062", "status-damage-ship-alliance-dauntless-cruiser_mc80a-homeone-cruiser" },
                { "10112", "status-damage-ship-empire-strike-cruiser_vindicator-heavy-cruiser" },
                { "10113", "status-damage-ship-empire-lancer-frigate" },
                { "10114", "status-damage-ship-empire-interdictor-cruiser_immobilizer-cruiser" },
                { "10115", "status-damage-ship-empire-carrack-light-cruiser_arquitens-light-cruiser" },
                { "10116", "status-damage-ship-empire-victory-destroyer_victory-1-star-destroyer" },
                { "10117", "status-damage-ship-empire-imperial-star-destroyer_imperial-1-star-destroyer" },
                { "10118", "status-damage-ship-empire-super-star-destroyer" },
                { "10119", "status-damage-ship-empire-assault-transport_gladiator-star-destroyer" },
                { "10120", "status-damage-ship-empire-death-star" },
                { "10121", "status-damage-ship-empire-galleon_acclamator-drop-ship" },
                { "10122", "status-damage-ship-empire-victory-2-star-destroyer" },
                { "10123", "status-damage-ship-empire-imperial-2-star-destroyer" },
                { "10124", "status-damage-ship-empire-star-galleon_star-galleon-frigate" },
                { "10125", "status-damage-ship-empire-imperial-escort-carrier" },
                { "10126", "status-damage-ship-empire-imperial-dreadnaught_imperial-dreadnought" },
                // empty (status window)
                { "14151", "status-empty" },
                // facilities
                { "16385", "facility-mine" },
                { "16386", "facility-refinery" },
                { "16640", "facility-orbital-shipyard" },
                { "16641", "facility-training-facility" },
                { "16642", "facility-construction-yard" },
                { "16643", "facility-advanced-shipyard" },
                { "16644", "facility-advanced-training-facility" },
                { "16645", "facility-advanced-construction-yard" },
                { "16896", "facility-kdy-150" },
                { "16897", "facility-lnr-series-1" },
                { "16898", "facility-gencore-level-1" },
                { "16899", "facility-lnr-series-2" },
                { "16900", "facility-gencore-level-2" },
                { "17024", "facility-death-star-shield" },
                { "17216", "facility-alliance-headquarters" },
                // troops
                { "17472", "troop-alliance-alliance-fleet-regiment" },
                { "17473", "troop-alliance-alliance-army-regiment" },
                { "17474", "troop-alliance-sullustan-regiment" },
                { "17475", "troop-alliance-wookiee-regiment" },
                { "17476", "troop-alliance-mon-calamari-regiment" },
                { "17536", "troop-empire-stormtrooper-regiment" },
                { "17537", "troop-empire-imperial-fleet-regiment" },
                { "17538", "troop-empire-imperial-army-regiment" },
                { "17539", "troop-empire-war-droid-regiment" },
                { "17540", "troop-empire-dark-trooper-regiment" },
                // special forces
                { "17728", "special-force-alliance-guerillas" },
                { "17729", "special-force-alliance-infiltrators" },
                { "17730", "special-force-alliance-longprobe-y-wing-recon-team" },
                { "17731", "special-force-alliance-bothan-spies" },
                { "17792", "special-force-empire-imperial-probe-droid" },
                { "17793", "special-force-empire-imperial-espionage-droid" },
                { "17794", "special-force-empire-imperial-commandos" },
                { "17795", "special-force-empire-noghri-death-commandos" },
                { "17796", "special-force-empire-bounty-hunters" },
                // fighters
                { "17984", "fighter-alliance-a-wing" },
                { "17985", "fighter-alliance-b-wing" },
                { "17986", "fighter-alliance-x-wing" },
                { "17987", "fighter-alliance-y-wing" },
                { "18048", "fighter-empire-tie-fighter" },
                { "18049", "fighter-empire-tie-interceptor" },
                { "18050", "fighter-empire-tie-bomber" },
                { "18051", "fighter-empire-tie-defender" },
                // capital ships
                { "18240", "ship-alliance-mon-calamari-cruiser_mc80-liberty-cruiser" },
                { "18241", "ship-alliance-bulk-cruiser" },
                { "18242", "ship-alliance-assault-frigate" },
                { "18243", "ship-alliance-nebulon-b-frigate" },
                { "18244", "ship-alliance-alliance-escort-carrier" },
                { "18245", "ship-alliance-corellian-corvette" },
                { "18246", "ship-alliance-medium-transport" },
                { "18247", "ship-alliance-bulk-transport_bulk-freighter" },
                { "18248", "ship-alliance-corellian-gunship" },
                { "18249", "ship-alliance-alliance-dreadnaught_mc40a-light-cruiser" },
                { "18250", "ship-alliance-cc-7700-frigate" },
                { "18251", "ship-alliance-bulwark-battlecruiser_viscount-star-defender" },
                { "18252", "ship-alliance-liberator-cruiser" },
                { "18253", "ship-alliance-cc-9600-frigate_mc30c-frigate" },
                { "18254", "ship-alliance-dauntless-cruiser_mc80a-homeone-cruiser" },
                { "18304", "ship-empire-strike-cruiser_vindicator-heavy-cruiser" },
                { "18305", "ship-empire-lancer-frigate" },
                { "18306", "ship-empire-interdictor-cruiser_immobilizer-cruiser" },
                { "18307", "ship-empire-carrack-light-cruiser_arquitens-light-cruiser" },
                { "18308", "ship-empire-victory-destroyer_victory-1-star-destroyer" },
                { "18309", "ship-empire-imperial-star-destroyer_imperial-1-star-destroyer" },
                { "18310", "ship-empire-super-star-destroyer" },
                { "18311", "ship-empire-assault-transport_gladiator-star-destroyer" },
                { "18312", "ship-empire-death-star" },
                { "18313", "ship-empire-galleon_acclamator-drop-ship" },
                { "18314", "ship-empire-victory-2-star-destroyer" },
                { "18315", "ship-empire-imperial-2-star-destroyer" },
                { "18316", "ship-empire-star-galleon_star-galleon-frigate" },
                { "18317", "ship-empire-imperial-escort-carrier" },
                { "18318", "ship-empire-imperial-dreadnaught_imperial-dreadnought" },
                // characters
                { "18496", "character-alliance-mon-mothma" },
                { "18497", "character-alliance-leia-organa" },
                { "18498", "character-alliance-luke-skywalker" },
                { "18499", "character-alliance-han-solo" },
                { "18512", "character-alliance-luke-knight" },
                { "18560", "character-empire-emperor-palpatine" },
                { "18561", "character-empire-darth-vader" },
                { "19008", "character-alliance-ackbar" },
                { "19009", "character-alliance-wedge-antilles" },
                { "19010", "character-alliance-lando-calrissian" },
                { "19011", "character-alliance-chewbacca" },
                { "19012", "character-alliance-jan-dodonna" },
                { "19013", "character-alliance-crix-madine" },
                { "19014", "character-alliance-carlist-rieekan" },
                { "19015", "character-alliance-afyon" },
                { "19016", "character-alliance-drayson" },
                { "19017", "character-alliance-borsk-fey'lya" },
                { "19018", "character-alliance-tura-raftican" },
                { "19019", "character-alliance-bren-derlin" },
                { "19020", "character-alliance-garm-bel-iblis" },
                { "19021", "character-alliance-talon-karrde" },
                { "19022", "character-alliance-narra" },
                { "19023", "character-alliance-huoba-neva" },
                { "19024", "character-alliance-page" },
                { "19025", "character-alliance-syub-snunb" },
                { "19026", "character-alliance-adar-tallon" },
                { "19027", "character-alliance-sarin-virgilio" },
                { "19028", "character-alliance-vanden-willard" },
                { "19029", "character-alliance-roget-jiriss" },
                { "19030", "character-alliance-kaiya-andrimetrum" },
                { "19031", "character-alliance-mazer-rackus" },
                { "19032", "character-alliance-orrimaarko" },
                { "19033", "character-alliance-ma'w'shiye" },
                { "19072", "character-empire-jerjerrod" },
                { "19073", "character-empire-ozzel" },
                { "19074", "character-empire-piett" },
                { "19075", "character-empire-veers" },
                { "19076", "character-empire-brandei" },
                { "19077", "character-empire-covell" },
                { "19078", "character-empire-dorja" },
                { "19079", "character-empire-bin-essada" },
                { "19080", "character-empire-niles-ferrier" },
                { "19081", "character-empire-grammel" },
                { "19082", "character-empire-griff" },
                { "19083", "character-empire-klev" },
                { "19084", "character-empire-needa" },
                { "19085", "character-empire-bane-nothos" },
                { "19086", "character-empire-orlok" },
                { "19087", "character-empire-pellaeon" },
                { "19088", "character-empire-screed" },
                { "19089", "character-empire-thrawn" },
                { "19090", "character-empire-zuggs" },
                { "19091", "character-empire-daala" },
                { "19092", "character-empire-pter-thanas" },
                { "19093", "character-empire-bevel-lemelisk" },
                { "19094", "character-empire-shenir-rix" },
                { "19095", "character-empire-noval-garaint" },
                { "19096", "character-empire-garindan" },
                { "19097", "character-empire-menndo" },
                { "19098", "character-empire-labansat" },
                { "19099", "character-empire-villar" },
                // missions alliance
                { "19472", "mission-alliance-diplomacy" },
                { "19473", "mission-alliance-rescue" },
                { "19474", "mission-alliance-sabotage" },
                { "19475", "mission-alliance-espionage" },
                { "19476", "mission-alliance-ship-design-research" },
                { "19477", "mission-alliance-reconnaissance" },
                { "19478", "mission-alliance-recruitment" },
                { "19479", "mission-alliance-abduction" },
                { "19488", "mission-alliance-ship-design-research" },
                { "19489", "mission-alliance-facility-design-research" },
                { "19490", "mission-alliance-troop-training-research" },
                { "19520", "mission-alliance-incite-uprising" },
                { "19521", "mission-alliance-death-star-sabotage" },
                { "19522", "mission-alliance-jedi-training" },
                { "19523", "mission-alliance-jedi-training" },
                { "19524", "mission-alliance-rescue" },
                { "19525", "mission-alliance-jedi-training" },
                { "19526", "mission-alliance-jedi-training" },
                { "19584", "mission-alliance-subdue-uprising" },
                { "19585", "mission-alliance-assassination" },
                { "19586", "mission-alliance-abduction" },
                { "19587", "mission-alliance-abduction" },
                // hyperspace overlays
                { "21569", "hyperspace-alliance" },
                { "21634", "hyperspace-empire" },
                { "21826", "hyperspace-alliance-longprobe-y-wing-recon-team" },
                { "21888", "hyperspace-empire-imperial-espionage-droid" },
                // reactors for fighters overlays
                { "22080", "reactors-fighter-alliance-a-wing" },
                { "22081", "reactors-fighter-alliance-b-wing" },
                { "22082", "reactors-fighter-alliance-x-wing" },
                { "22083", "reactors-fighter-alliance-y-wing" },
                { "22144", "reactors-fighter-empire-tie-fighter" },
                { "22145", "reactors-fighter-empire-tie-interceptor" },
                { "22146", "reactors-fighter-empire-tie-bomber" },
                { "22147", "reactors-fighter-empire-tie-defender" },
                // reactors for capital ships overlays
                { "22336", "reactors-ship-alliance-mon-calamari-cruiser_mc80-liberty-cruiser" },
                { "22337", "reactors-ship-alliance-bulk-cruiser" },
                { "22338", "reactors-ship-alliance-assault-frigate" },
                { "22339", "reactors-ship-alliance-nebulon-b-frigate" },
                { "22340", "reactors-ship-alliance-alliance-escort-carrier" },
                { "22341", "reactors-ship-alliance-corellian-corvette" },
                { "22342", "reactors-ship-alliance-medium-transport" },
                { "22343", "reactors-ship-alliance-bulk-transport_bulk-freighter" },
                { "22344", "reactors-ship-alliance-corellian-gunship" },
                { "22345", "reactors-ship-alliance-alliance-dreadnaught_mc40a-light-cruiser" },
                { "22346", "reactors-ship-alliance-cc-7700-frigate" },
                { "22347", "reactors-ship-alliance-bulwark-battlecruiser_viscount-star-defender" },
                { "22348", "reactors-ship-alliance-liberator-cruiser" },
                { "22349", "reactors-ship-alliance-cc-9600-frigate_mc30c-frigate" },
                { "22350", "reactors-ship-alliance-dauntless-cruiser_mc80a-homeone-cruiser" },
                { "22400", "reactors-ship-empire-strike-cruiser_vindicator-heavy-cruiser" },
                { "22401", "reactors-ship-empire-lancer-frigate" },
                { "22402", "reactors-ship-empire-interdictor-cruiser_immobilizer-cruiser" },
                { "22403", "reactors-ship-empire-carrack-light-cruiser_arquitens-light-cruiser" },
                { "22404", "reactors-ship-empire-victory-destroyer_victory-1-star-destroyer" },
                { "22405", "reactors-ship-empire-imperial-star-destroyer_imperial-1-star-destroyer" },
                { "22406", "reactors-ship-empire-super-star-destroyer" },
                { "22407", "reactors-ship-empire-assault-transport_gladiator-star-destroyer" },
                { "22408", "reactors-ship-empire-death-star" },
                { "22409", "reactors-ship-empire-galleon_acclamator-drop-ship" },
                { "22410", "reactors-ship-empire-victory-2-star-destroyer" },
                { "22411", "reactors-ship-empire-imperial-2-star-destroyer" },
                { "22412", "reactors-ship-empire-star-galleon_star-galleon-frigate" },
                { "22413", "reactors-ship-empire-imperial-escort-carrier" },
                { "22414", "reactors-ship-empire-imperial-dreadnaught_imperial-dreadnought" },
                // missions empire
                { "23568", "mission-empire-diplomacy" },
                { "23569", "mission-empire-rescue" },
                { "23570", "mission-empire-sabotage" },
                { "23571", "mission-empire-espionage" },
                { "23572", "mission-empire-ship-design-research" },
                { "23573", "mission-empire-reconnaissance" },
                { "23574", "mission-empire-recruitment" },
                { "23575", "mission-empire-abduction" },
                { "23584", "mission-empire-ship-design-research" },
                { "23585", "mission-empire-facility-design-research" },
                { "23586", "mission-empire-troop-training-research" },
                { "23616", "mission-empire-incite-uprising" },
                { "23617", "mission-empire-death-star-sabotage" },
                { "23618", "mission-empire-jedi-training" },
                { "23619", "mission-empire-jedi-training" },
                { "23620", "mission-empire-rescue" },
                { "23621", "mission-empire-jedi-training" },
                { "23622", "mission-empire-jedi-training" },
                { "23680", "mission-empire-subdue-uprising" },
                { "23681", "mission-empire-assassination" },
                { "23682", "mission-empire-abduction" },
                { "23683", "mission-empire-abduction" },
                // damage on fighters
                { "26176", "damage-fighter-alliance-a-wing" },
                { "26177", "damage-fighter-alliance-b-wing" },
                { "26178", "damage-fighter-alliance-x-wing" },
                { "26179", "damage-fighter-alliance-y-wing" },
                { "26240", "damage-fighter-empire-tie-fighter" },
                { "26241", "damage-fighter-empire-tie-interceptor" },
                { "26242", "damage-fighter-empire-tie-bomber" },
                { "26243", "damage-fighter-empire-tie-defender" },
                // damage on capital ships
                { "26432", "damage-ship-alliance-mon-calamari-cruiser_mc80-liberty-cruiser" },
                { "26433", "damage-ship-alliance-bulk-cruiser" },
                { "26434", "damage-ship-alliance-assault-frigate" },
                { "26435", "damage-ship-alliance-nebulon-b-frigate" },
                { "26436", "damage-ship-alliance-alliance-escort-carrier" },
                { "26437", "damage-ship-alliance-corellian-corvette" },
                { "26438", "damage-ship-alliance-medium-transport" },
                { "26439", "damage-ship-alliance-bulk-transport_bulk-freighter" },
                { "26440", "damage-ship-alliance-corellian-gunship" },
                { "26441", "damage-ship-alliance-alliance-dreadnaught_mc40a-light-cruiser" },
                { "26442", "damage-ship-alliance-cc-7700-frigate" },
                { "26443", "damage-ship-alliance-bulwark-battlecruiser_viscount-star-defender" },
                { "26444", "damage-ship-alliance-liberator-cruiser" },
                { "26445", "damage-ship-alliance-cc-9600-frigate_mc30c-frigate" },
                { "26446", "damage-ship-alliance-dauntless-cruiser_mc80a-homeone-cruiser" },
                { "26496", "damage-ship-empire-strike-cruiser_vindicator-heavy-cruiser" },
                { "26497", "damage-ship-empire-lancer-frigate" },
                { "26498", "damage-ship-empire-interdictor-cruiser_immobilizer-cruiser" },
                { "26499", "damage-ship-empire-carrack-light-cruiser_arquitens-light-cruiser" },
                { "26500", "damage-ship-empire-victory-destroyer_victory-1-star-destroyer" },
                { "26501", "damage-ship-empire-imperial-star-destroyer_imperial-1-star-destroyer" },
                { "26502", "damage-ship-empire-super-star-destroyer" },
                { "26503", "damage-ship-empire-assault-transport_gladiator-star-destroyer" },
                { "26504", "damage-ship-empire-death-star" },
                { "26505", "damage-ship-empire-galleon_acclamator-drop-ship" },
                { "26506", "damage-ship-empire-victory-2-star-destroyer" },
                { "26507", "damage-ship-empire-imperial-2-star-destroyer" },
                { "26508", "damage-ship-empire-star-galleon_star-galleon-frigate" },
                { "26509", "damage-ship-empire-imperial-escort-carrier" },
                { "26510", "damage-ship-empire-imperial-dreadnaught_imperial-dreadnought" },
                // jail overlay for characters
                { "30535", "jail-empty" },
                { "30784", "jail-character-alliance-mon-mothma" },
                { "30785", "jail-character-alliance-leia-organa" },
                { "30786", "jail-character-alliance-luke-skywalker" },
                { "30787", "jail-character-alliance-han-solo" },
                { "30800", "jail-character-alliance-luke-knight" },
                { "30848", "jail-character-empire-emperor-palpatine" },
                { "30849", "jail-character-empire-darth-vader" },
                { "31296", "jail-character-alliance-ackbar" },
                { "31297", "jail-character-alliance-wedge-antilles" },
                { "31298", "jail-character-alliance-lando-calrissian" },
                { "31299", "jail-character-alliance-chewbacca" },
                { "31300", "jail-character-alliance-jan-dodonna" },
                { "31301", "jail-character-alliance-crix-madine" },
                { "31302", "jail-character-alliance-carlist-rieekan" },
                { "31303", "jail-character-alliance-afyon" },
                { "31304", "jail-character-alliance-drayson" },
                { "31305", "jail-character-alliance-borsk-fey'lya" },
                { "31306", "jail-character-alliance-tura-raftican" },
                { "31307", "jail-character-alliance-bren-derlin" },
                { "31308", "jail-character-alliance-garm-bel-iblis" },
                { "31309", "jail-character-alliance-talon-karrde" },
                { "31310", "jail-character-alliance-narra" },
                { "31311", "jail-character-alliance-huoba-neva" },
                { "31312", "jail-character-alliance-page" },
                { "31313", "jail-character-alliance-syub-snunb" },
                { "31314", "jail-character-alliance-adar-tallon" },
                { "31315", "jail-character-alliance-sarin-virgilio" },
                { "31316", "jail-character-alliance-vanden-willard" },
                { "31317", "jail-character-alliance-roget-jiriss" },
                { "31318", "jail-character-alliance-kaiya-andrimetrum" },
                { "31319", "jail-character-alliance-mazer-rackus" },
                { "31320", "jail-character-alliance-orrimaarko" },
                { "31321", "jail-character-alliance-ma'w'shiye" },
                { "31360", "jail-character-empire-jerjerrod" },
                { "31361", "jail-character-empire-ozzel" },
                { "31362", "jail-character-empire-piett" },
                { "31363", "jail-character-empire-veers" },
                { "31364", "jail-character-empire-brandei" },
                { "31365", "jail-character-empire-covell" },
                { "31366", "jail-character-empire-dorja" },
                { "31367", "jail-character-empire-bin-essada" },
                { "31368", "jail-character-empire-niles-ferrier" },
                { "31369", "jail-character-empire-grammel" },
                { "31370", "jail-character-empire-griff" },
                { "31371", "jail-character-empire-klev" },
                { "31372", "jail-character-empire-needa" },
                { "31373", "jail-character-empire-bane-nothos" },
                { "31374", "jail-character-empire-orlok" },
                { "31375", "jail-character-empire-pellaeon" },
                { "31376", "jail-character-empire-screed" },
                { "31377", "jail-character-empire-thrawn" },
                { "31378", "jail-character-empire-zuggs" },
                { "31379", "jail-character-empire-daala" },
                { "31380", "jail-character-empire-pter-thanas" },
                { "31381", "jail-character-empire-bevel-lemelisk" },
                { "31382", "jail-character-empire-shenir-rix" },
                { "31383", "jail-character-empire-noval-garaint" },
                { "31384", "jail-character-empire-garindan" },
                { "31385", "jail-character-empire-menndo" },
                { "31386", "jail-character-empire-labansat" },
                { "31387", "jail-character-empire-villar" },
        };
    }
}
