namespace SwRebellionEditor;

// WAVE, Bitmap, RCData, Version Info

public class Strategy : ResourcesDll
{
    public Strategy(string fileName) : base(fileName)
    {
        NamesBitmap = new Dictionary<string, string>
            {
                { "900", "command-bridge-rebel" },
                { "901", "command-bridge-empire" },
                { "902", "galaxy-display-off" },
                { "903", "galaxy-display-on" },
                { "904", "headquarters-rebel" },
                { "905", "uprising-rebel" },
                { "906", "uprising-empire" },
                { "1000", "informants" },
                { "1002", "resources-event" },
                { "1003", "natural-disaster" },
                { "1004", "smuggling-operation-begins" },
                { "1005", "planet-joins" },
                { "1006", "planet-neutrality" },
                { "1008", "planet-near-uprising-rebel" },
                { "1009", "planet-near-uprising-empire" },
                { "1010", "planet-uprising" },
                { "1011", "planet-uprising-subdued-rebel" },
                { "1012", "planet-uprising-subdued-empire" },
                { "1013", "sabotage-maintenance-explosion-rebel" },
                { "1014", "sabotage-maintenance-explosion-empire" },
                { "1017", "research" },
                { "1018", "fleet-arrives-rebel" },
                { "1019", "fleet-arrives-empire" },
                { "1020", "units-arrive-rebel" },
                { "1021", "units-arrive-empire" },
                { "1022", "headquarters-arrive-rebel" },
                { "1027", "planetary-blockade-rebel" },
                { "1028", "planetary-blockade-empire" },
                { "1029", "prisoner-escape" },
                { "1030", "planetary-blockade-breaching-fails-empire" },
                { "1031", "planetary-blockade-breaching-fails-rebel" },
                { "1032", "unit-facility-decommission-rebel" },
                { "1033", "unit-facility-decommission-empire" },
                { "1034", "character-retirement-rebel" },
                { "1035", "character-retirement-empire" },
                { "1040", "multiplayer-chat-rebel" },
                { "1041", "multiplayer-chat-empire" },
                { "1042", "character-reporting-background-rebel" },
                { "1043", "character-reporting-background-empire" },
                { "1044", "diplomacy-mission-background" },
                { "1045", "mission-background" },
                { "1046", "character-mission-foiled-rebel" },
                { "1047", "character-mission-foiled-empire" },
                { "1048", "rebel-character-captured-empire" },
                { "1049", "empire-character-captured-empire" },
                { "1050", "character-injured" },
                { "1051", "character-recovered" },
                { "1052", "bounty-hunters-defeated" },
                { "1053", "jabba-captures-solo" },
                { "1054", "bounty-hunters-locate-solo" },
                { "1055", "vader-vs-leia" },
                { "1056", "emperor-vs-leia" },
                { "1057", "luke-travels-dagobah" },
                { "1058", "luke-discovers-heritage" },
                { "1059", "vader-vs-student-luke" },
                { "1060", "vader-vs-knight-luke" },
                { "1061", "emperor-vs-student-luke" },
                { "1062", "emperor-vs-knight-luke" },
                { "1063", "emperor-vader-vs-student-luke" },
                { "1064", "emperor-vader-vs-knight-luke" },
                { "1065", "jabba-vs-luke" },
                { "1066", "bounty-hunters-capture-heroes-rebel" },
                { "1067", "bounty-hunters-capture-heroes-empire" },
                { "1068", "emperor-arrives-coruscant" },
                { "1070", "character-killed-rebel" },
                { "1071", "help-3po" },
                { "1072", "help-imp" },
                { "1073", "mission-foiled-rebel" },
                { "1074", "mission-foiled-empire" },
                { "1075", "character-killed-empire" },
                { "6208", "events-mon-mothma" },
                { "6209", "events-leia-organa" },
                { "6210", "events-luke-skywalker" },
                { "6211", "events-han-solo" },
                { "6224", "events-luke-knight" },
                { "6272", "events-emperor-palpatine" },
                { "6273", "events-darth-vader" },
                { "6720", "events-ackbar" },
                { "6721", "events-wedge-antilles" },
                { "6722", "events-lando-calrissian" },
                { "6723", "events-chewbacca" },
                { "6724", "events-jan-dodonna" },
                { "6725", "events-crix-madine" },
                { "6726", "events-carlist-rieekan" },
                { "6727", "events-afyon" },
                { "6728", "events-drayson" },
                { "6729", "events-borsk-fey'lya" },
                { "6730", "events-tura-raftican" },
                { "6731", "events-bren-derlin" },
                { "6732", "events-garm-bel-iblis" },
                { "6733", "events-talon-karrde" },
                { "6734", "events-narra" },
                { "6735", "events-huoba-neva" },
                { "6736", "events-page" },
                { "6737", "events-syub-snunb" },
                { "6738", "events-adar-tallon" },
                { "6739", "events-sarin-virgilio" },
                { "6740", "events-vanden-willard" },
                { "6741", "events-roget-jiriss" },
                { "6742", "events-kaiya-andrimetrum" },
                { "6743", "events-mazer-rackus" },
                { "6744", "events-orrimaarko" },
                { "6745", "events-ma'w'shiye" },
                { "6784", "events-jerjerrod" },
                { "6785", "events-ozzel" },
                { "6786", "events-piett" },
                { "6787", "events-veers" },
                { "6788", "events-brandei" },
                { "6789", "events-covell" },
                { "6790", "events-dorja" },
                { "6791", "events-bin-essada" },
                { "6792", "events-niles-ferrier" },
                { "6793", "events-grammel" },
                { "6794", "events-griff" },
                { "6795", "events-klev" },
                { "6796", "events-needa" },
                { "6797", "events-bane-nothos" },
                { "6798", "events-orlok" },
                { "6799", "events-pellaeon" },
                { "6800", "events-screed" },
                { "6801", "events-thrawn" },
                { "6802", "events-zuggs" },
                { "6803", "events-daala" },
                { "6804", "events-pter-thanas" },
                { "6805", "events-bevel-lemelisk" },
                { "6806", "events-shenir-rix" },
                { "6807", "events-noval-garaint" },
                { "6808", "events-garindan" },
                { "6809", "events-menndo" },
                { "6810", "events-labansat" },
                { "6811", "events-villar" },
                { "11000", "info-ackbar" },
                { "11001", "info-afyon" },
                { "11002", "info-kaiya-andrimetrum" },
                { "11003", "info-wedge-antilles" },
                { "11004", "info-brandei" },
                { "11005", "info-lando-calrissian" },
                { "11006", "info-chewbacca" },
                { "11007", "info-covell" },
                { "11008", "info-daala" },
                { "11009", "info-bren-derlin" },
                { "11010", "info-jan-dodonna" },
                { "11011", "info-dorja" },
                { "11012", "info-drayson" },
                { "11013", "info-emperor-palpatine" },
                { "11014", "info-bin-essada" },
                { "11015", "info-niles-ferrier" },
                { "11016", "info-borsk-fey'lya" },
                { "11017", "info-griff" },
                { "11018", "info-grammel" },
                { "11019", "info-garm-bel-iblis" },
                { "11020", "info-garindan" },
                { "11021", "info-jerjerrod" },
                { "11022", "info-roget-jiriss" },
                { "11023", "info-talon-karrde" },
                { "11024", "info-klev" },
                { "11025", "info-labansat" },
                { "11026", "info-bevel-lemelisk" },
                { "11027", "info-luke-knight" },
                { "11028", "info-luke-skywalker" },
                { "11029", "info-crix-madine" },
                { "11030", "info-ma'w'shiye" },
                { "11031", "info-menndo" },
                { "11032", "info-mon-mothma" },
                { "11033", "info-narra" },
                { "11034", "info-needa" },
                { "11035", "info-huoba-neva" },
                { "11036", "info-bane-nothos" },
                { "11037", "info-noval-garaint" },
                { "11038", "info-leia-organa" },
                { "11039", "info-orlok" },
                { "11040", "info-orrimaarko" },
                { "11041", "info-ozzel" },
                { "11042", "info-page" },
                { "11043", "info-pellaeon" },
                { "11044", "info-piett" },
                { "11045", "info-mazer-rackus" },
                { "11046", "info-tura-raftican" },
                { "11047", "info-carlist-rieekan" },
                { "11048", "info-shenir-rix" },
                { "11049", "info-screed" },
                { "11050", "info-syub-snunb" },
                { "11051", "info-han-solo" },
                { "11052", "info-adar-tallon" },
                { "11053", "info-pter-thanas" },
                { "11054", "info-thrawn" },
                { "11055", "info-darth-vader" },
                { "11056", "info-veers" },
                { "11057", "info-villar" },
                { "11058", "info-sarin-virgilio" },
                { "11059", "info-vanden-willard" },
                { "11060", "info-zuggs" },
            };
        NamesWave = new Dictionary<string, string>
            {
                {"620", "planetary-assault" },
                {"621", "orbital-bombardment" },
                {"1100", "informants" },
                {"1101", "construction-complete" },
                {"1102", "natural-disaster" },
                {"1103", "smuggling-operation-begins" },
                {"1104", "planet-joins" },
                {"1105", "planet-neutrality" },
                {"1106", "planet-near-uprising-empire" },
                {"1107", "planet-near-uprising-rebel" },
                {"1108", "planet-uprising" },
                {"1109", "planet-uprising-subdued" },
                {"1110", "sabotage-maintenance-explosion" },
                {"1111", "squadron-arrives-rebel" },
                {"1112", "squadron-arrives-empire" },
                {"1113", "research-successful" },
                {"1114", "fleet-arrives" },
                {"1115", "units-arrive-rebel" },
                {"1116", "units-arrive-empire" },
                {"1117", "headquarters-arrive-rebel" },
                {"1118", "planetary-blockade" },
                {"1119", "planetary-blockade-breaching-fails-empire" },
                {"1120", "planetary-blockade-breaching-fails-rebel" },
                {"1129", "prisoner-escape" },
                {"1136", "emperor-vs-luke" },
                {"1140", "character-injured" },
                {"1142", "jabba-court" },
                {"1144", "jabba-unknown" },
        };
    }
}
