namespace SwRebellionEditor;

public class Tactical : ResourcesDll
{
    public Tactical(string fileName) : base(fileName)
    {
        Names301 = new Dictionary<string, string>
            {
                // capital ships 3d models
                { "2010", "ship-alliance-mon-calamari-cruiser_mc80-liberty-cruiser-close" },
                { "2011", "ship-alliance-mon-calamari-cruiser_mc80-liberty-cruiser-medium" },
                { "2012", "ship-alliance-mon-calamari-cruiser_mc80-liberty-cruiser-far" },
                { "2020", "ship-alliance-bulk-cruiser-close" },
                { "2021", "ship-alliance-bulk-cruiser-medium" },
                { "2022", "ship-alliance-bulk-cruiser-far" },
                { "2030", "ship-alliance-assault-frigate-close" },
                { "2031", "ship-alliance-assault-frigate-medium" },
                { "2032", "ship-alliance-assault-frigate-far" },
                { "2040", "ship-alliance-nebulon-b-frigate-close" },
                { "2041", "ship-alliance-nebulon-b-frigate-medium" },
                { "2042", "ship-alliance-nebulon-b-frigate-far" },
                { "2050", "ship-alliance-alliance-escort-carrier-close" },
                { "2051", "ship-alliance-alliance-escort-carrier-medium" },
                { "2052", "ship-alliance-alliance-escort-carrier-far" },
                { "2060", "ship-alliance-corellian-corvette-close" },
                { "2061", "ship-alliance-corellian-corvette-medium" },
                { "2062", "ship-alliance-corellian-corvette-far" },
                { "2070", "ship-alliance-medium-transport-close" },
                { "2071", "ship-alliance-medium-transport-medium" },
                { "2072", "ship-alliance-medium-transport-far" },
                { "2080", "ship-alliance-bulk-transport_bulk-freighter-close" },
                { "2081", "ship-alliance-bulk-transport_bulk-freighter-medium" },
                { "2082", "ship-alliance-bulk-transport_bulk-freighter-far" },
                { "2090", "ship-alliance-corellian-gunship-close" },
                { "2091", "ship-alliance-corellian-gunship-medium" },
                { "2092", "ship-alliance-corellian-gunship-far" },
                { "2100", "ship-alliance-alliance-dreadnaught_mc40a-light-cruiser-close" },
                { "2101", "ship-alliance-alliance-dreadnaught_mc40a-light-cruiser-medium" },
                { "2102", "ship-alliance-alliance-dreadnaught_mc40a-light-cruiser-far" },
                { "2110", "ship-alliance-cc-7700-frigate-close" },
                { "2111", "ship-alliance-cc-7700-frigate-medium" },
                { "2112", "ship-alliance-cc-7700-frigate-far" },
                { "2120", "ship-alliance-cc-9600-frigate_mc30c-frigate-close" },
                { "2121", "ship-alliance-cc-9600-frigate_mc30c-frigate-medium" },
                { "2122", "ship-alliance-cc-9600-frigate_mc30c-frigate-far" },
                { "2130", "ship-alliance-bulwark-battlecruiser_viscount-star-defender-close" },
                { "2131", "ship-alliance-bulwark-battlecruiser_viscount-star-defender-medium" },
                { "2132", "ship-alliance-bulwark-battlecruiser_viscount-star-defender-far" },
                { "2140", "ship-alliance-liberator-cruiser-close" },
                { "2141", "ship-alliance-liberator-cruiser-medium" },
                { "2142", "ship-alliance-liberator-cruiser-far" },
                { "2150", "ship-alliance-dauntless-cruiser_mc80a-homeone-cruiser-close" },
                { "2151", "ship-alliance-dauntless-cruiser_mc80a-homeone-cruiser-medium" },
                { "2152", "ship-alliance-dauntless-cruiser_mc80a-homeone-cruiser-far" },
                { "2510", "ship-empire-strike-cruiser_vindicator-heavy-cruiser-close" },
                { "2511", "ship-empire-strike-cruiser_vindicator-heavy-cruiser-medium" },
                { "2512", "ship-empire-strike-cruiser_vindicator-heavy-cruiser-far" },
                { "2520", "ship-empire-lancer-frigate-close" },
                { "2521", "ship-empire-lancer-frigate-medium" },
                { "2522", "ship-empire-lancer-frigate-far" },
                { "2530", "ship-empire-interdictor-cruiser_immobilizer-cruiser-close" },
                { "2531", "ship-empire-interdictor-cruiser_immobilizer-cruiser-medium" },
                { "2532", "ship-empire-interdictor-cruiser_immobilizer-cruiser-far" },
                { "2540", "ship-empire-carrack-light-cruiser_arquitens-light-cruiser-close" },
                { "2541", "ship-empire-carrack-light-cruiser_arquitens-light-cruiser-medium" },
                { "2542", "ship-empire-carrack-light-cruiser_arquitens-light-cruiser-far" },
                { "2550", "ship-empire-victory-destroyer_victory-1-star-destroyer-close" },
                { "2551", "ship-empire-victory-destroyer_victory-1-star-destroyer-medium" },
                { "2552", "ship-empire-victory-destroyer_victory-1-star-destroyer-far" },
                { "2560", "ship-empire-imperial-star-destroyer_imperial-1-star-destroyer-close" },
                { "2561", "ship-empire-imperial-star-destroyer_imperial-1-star-destroyer-medium" },
                { "2562", "ship-empire-imperial-star-destroyer_imperial-1-star-destroyer-far" },
                { "2570", "ship-empire-super-star-destroyer-close" },
                { "2571", "ship-empire-super-star-destroyer-medium" },
                { "2572", "ship-empire-super-star-destroyer-far" },
                { "2580", "ship-empire-assault-transport_gladiator-star-destroyer-close" },
                { "2581", "ship-empire-assault-transport_gladiator-star-destroyer-medium" },
                { "2582", "ship-empire-assault-transport_gladiator-star-destroyer-far" },
                { "2590", "ship-empire-galleon_acclamator-drop-ship-close" },
                { "2591", "ship-empire-galleon_acclamator-drop-ship-medium" },
                { "2592", "ship-empire-galleon_acclamator-drop-ship-far" },
                { "2600", "ship-empire-victory-2-star-destroyer-close" },
                { "2601", "ship-empire-victory-2-star-destroyer-medium" },
                { "2602", "ship-empire-victory-2-star-destroyer-far" },
                { "2610", "ship-empire-imperial-2-star-destroyer-close" },
                { "2611", "ship-empire-imperial-2-star-destroyer-medium" },
                { "2612", "ship-empire-imperial-2-star-destroyer-far" },
                { "2620", "ship-empire-star-galleon_star-galleon-frigate-close" },
                { "2621", "ship-empire-star-galleon_star-galleon-frigate-medium" },
                { "2622", "ship-empire-star-galleon_star-galleon-frigate-far" },
                { "2630", "ship-empire-imperial-escort-carrier-close" },
                { "2631", "ship-empire-imperial-escort-carrier-medium" },
                { "2632", "ship-empire-imperial-escort-carrier-far" },
                { "2640", "ship-empire-imperial-dreadnaught_imperial-dreadnought-close" },
                { "2641", "ship-empire-imperial-dreadnaught_imperial-dreadnought-medium" },
                { "2642", "ship-empire-imperial-dreadnaught_imperial-dreadnought-far" },
            };
        Names303 = new Dictionary<string, string>
            {
                // fx
                { "3020" , "fx-orange-split-blast-far-1" },
                { "3021" , "fx-orange-split-blast-far-2" },
                { "3022" , "fx-orange-split-blast-far-3" },
                { "3023" , "fx-orange-split-blast-far-4" },
                { "3024" , "fx-orange-split-blast-far-5" },
                { "3025" , "fx-orange-split-blast-far-6" },
                { "3040" , "fx-orange-split-blast-medium-1" },
                { "3041" , "fx-orange-split-blast-medium-2" },
                { "3042" , "fx-orange-split-blast-medium-3" },
                { "3043" , "fx-orange-split-blast-medium-4" },
                { "3044" , "fx-orange-split-blast-medium-5" },
                { "3045" , "fx-orange-split-blast-medium-6" },
                { "3060" , "fx-orange-split-blast-close-1" },
                { "3061" , "fx-orange-split-blast-close-2" },
                { "3062" , "fx-orange-split-blast-close-3" },
                { "3063" , "fx-orange-split-blast-close-4" },
                { "3064" , "fx-orange-split-blast-close-5" },
                { "3065" , "fx-orange-split-blast-close-6" },
                { "3080" , "fx-orange-blast-far-1" },
                { "3081" , "fx-orange-blast-far-2" },
                { "3082" , "fx-orange-blast-far-3" },
                { "3083" , "fx-orange-blast-far-4" },
                { "3084" , "fx-orange-blast-far-5" },
                { "3085" , "fx-orange-blast-far-6" },
                { "3086" , "fx-orange-blast-far-7" },
                { "3100" , "fx-orange-blast-medium-1" },
                { "3101" , "fx-orange-blast-medium-2" },
                { "3102" , "fx-orange-blast-medium-3" },
                { "3103" , "fx-orange-blast-medium-4" },
                { "3104" , "fx-orange-blast-medium-5" },
                { "3105" , "fx-orange-blast-medium-6" },
                { "3106" , "fx-orange-blast-medium-7" },
                { "3120" , "fx-orange-blast-close-1" },
                { "3121" , "fx-orange-blast-close-2" },
                { "3122" , "fx-orange-blast-close-3" },
                { "3123" , "fx-orange-blast-close-4" },
                { "3124" , "fx-orange-blast-close-5" },
                { "3125" , "fx-orange-blast-close-6" },
                { "3126" , "fx-orange-blast-close-7" },
                { "3140" , "fx-blue-spread-far-1" },
                { "3141" , "fx-blue-spread-far-2" },
                { "3142" , "fx-blue-spread-far-3" },
                { "3143" , "fx-blue-spread-far-4" },
                { "3144" , "fx-blue-spread-far-5" },
                { "3145" , "fx-blue-spread-far-6" },
                { "3160" , "fx-blue-spread-medium-1" },
                { "3161" , "fx-blue-spread-medium-2" },
                { "3162" , "fx-blue-spread-medium-3" },
                { "3163" , "fx-blue-spread-medium-4" },
                { "3164" , "fx-blue-spread-medium-5" },
                { "3165" , "fx-blue-spread-medium-6" },
                { "3180" , "fx-blue-spread-close-1" },
                { "3181" , "fx-blue-spread-close-2" },
                { "3182" , "fx-blue-spread-close-3" },
                { "3183" , "fx-blue-spread-close-4" },
                { "3184" , "fx-blue-spread-close-5" },
                { "3185" , "fx-blue-spread-close-6" },
                { "3200" , "fx-blue-net-far-01" },
                { "3201" , "fx-blue-net-far-02" },
                { "3202" , "fx-blue-net-far-03" },
                { "3203" , "fx-blue-net-far-04" },
                { "3204" , "fx-blue-net-far-05" },
                { "3205" , "fx-blue-net-far-06" },
                { "3206" , "fx-blue-net-far-07" },
                { "3207" , "fx-blue-net-far-08" },
                { "3208" , "fx-blue-net-far-09" },
                { "3209" , "fx-blue-net-far-10" },
                { "3210" , "fx-blue-net-far-11" },
                { "3211" , "fx-blue-net-far-12" },
                { "3212" , "fx-blue-net-far-13" },
                { "3213" , "fx-blue-net-far-14" },
                { "3214" , "fx-blue-net-far-15" },
                { "3215" , "fx-blue-net-far-16" },
                { "3220" , "fx-blue-net-medium-01" },
                { "3221" , "fx-blue-net-medium-02" },
                { "3222" , "fx-blue-net-medium-03" },
                { "3223" , "fx-blue-net-medium-04" },
                { "3224" , "fx-blue-net-medium-05" },
                { "3225" , "fx-blue-net-medium-06" },
                { "3226" , "fx-blue-net-medium-07" },
                { "3227" , "fx-blue-net-medium-08" },
                { "3228" , "fx-blue-net-medium-09" },
                { "3229" , "fx-blue-net-medium-10" },
                { "3230" , "fx-blue-net-medium-11" },
                { "3231" , "fx-blue-net-medium-12" },
                { "3232" , "fx-blue-net-medium-13" },
                { "3233" , "fx-blue-net-medium-14" },
                { "3234" , "fx-blue-net-medium-15" },
                { "3235" , "fx-blue-net-medium-16" },
                { "3240" , "fx-blue-net-close-01" },
                { "3241" , "fx-blue-net-close-02" },
                { "3242" , "fx-blue-net-close-03" },
                { "3243" , "fx-blue-net-close-04" },
                { "3244" , "fx-blue-net-close-05" },
                { "3245" , "fx-blue-net-close-06" },
                { "3246" , "fx-blue-net-close-07" },
                { "3247" , "fx-blue-net-close-08" },
                { "3248" , "fx-blue-net-close-09" },
                { "3249" , "fx-blue-net-close-10" },
                { "3250" , "fx-blue-net-close-11" },
                { "3251" , "fx-blue-net-close-12" },
                { "3252" , "fx-blue-net-close-13" },
                { "3253" , "fx-blue-net-close-14" },
                { "3254" , "fx-blue-net-close-15" },
                { "3255" , "fx-blue-net-close-16" },
                { "3260" , "fx-blue-blast-far-1" },
                { "3261" , "fx-blue-blast-far-2" },
                { "3262" , "fx-blue-blast-far-3" },
                { "3263" , "fx-blue-blast-far-4" },
                { "3264" , "fx-blue-blast-far-5" },
                { "3265" , "fx-blue-blast-far-6" },
                { "3266" , "fx-blue-blast-far-7" },
                { "3280" , "fx-blue-blast-medium-1" },
                { "3281" , "fx-blue-blast-medium-2" },
                { "3282" , "fx-blue-blast-medium-3" },
                { "3283" , "fx-blue-blast-medium-4" },
                { "3284" , "fx-blue-blast-medium-5" },
                { "3285" , "fx-blue-blast-medium-6" },
                { "3286" , "fx-blue-blast-medium-7" },
                { "3300" , "fx-blue-blast-close-1" },
                { "3301" , "fx-blue-blast-close-2" },
                { "3302" , "fx-blue-blast-close-3" },
                { "3303" , "fx-blue-blast-close-4" },
                { "3304" , "fx-blue-blast-close-5" },
                { "3305" , "fx-blue-blast-close-6" },
                { "3306" , "fx-blue-blast-close-7" },
                { "3320" , "fx-orange-double-blast-far-01" },
                { "3321" , "fx-orange-double-blast-far-02" },
                { "3322" , "fx-orange-double-blast-far-03" },
                { "3323" , "fx-orange-double-blast-far-04" },
                { "3324" , "fx-orange-double-blast-far-05" },
                { "3325" , "fx-orange-double-blast-far-06" },
                { "3326" , "fx-orange-double-blast-far-07" },
                { "3327" , "fx-orange-double-blast-far-08" },
                { "3328" , "fx-orange-double-blast-far-09" },
                { "3329" , "fx-orange-double-blast-far-10" },
                { "3330" , "fx-orange-double-blast-far-11" },
                { "3331" , "fx-orange-double-blast-far-12" },
                { "3332" , "fx-orange-double-blast-far-13" },
                { "3333" , "fx-orange-double-blast-far-14" },
                { "3334" , "fx-orange-double-blast-far-15" },
                { "3335" , "fx-orange-double-blast-far-16" },
                { "3340" , "fx-orange-double-blast-medium-01" },
                { "3341" , "fx-orange-double-blast-medium-02" },
                { "3342" , "fx-orange-double-blast-medium-03" },
                { "3343" , "fx-orange-double-blast-medium-04" },
                { "3344" , "fx-orange-double-blast-medium-05" },
                { "3345" , "fx-orange-double-blast-medium-06" },
                { "3346" , "fx-orange-double-blast-medium-07" },
                { "3347" , "fx-orange-double-blast-medium-08" },
                { "3348" , "fx-orange-double-blast-medium-09" },
                { "3349" , "fx-orange-double-blast-medium-10" },
                { "3350" , "fx-orange-double-blast-medium-11" },
                { "3351" , "fx-orange-double-blast-medium-12" },
                { "3352" , "fx-orange-double-blast-medium-13" },
                { "3353" , "fx-orange-double-blast-medium-14" },
                { "3354" , "fx-orange-double-blast-medium-15" },
                { "3355" , "fx-orange-double-blast-medium-16" },
                { "3360" , "fx-orange-double-blast-close-01" },
                { "3361" , "fx-orange-double-blast-close-02" },
                { "3362" , "fx-orange-double-blast-close-03" },
                { "3363" , "fx-orange-double-blast-close-04" },
                { "3364" , "fx-orange-double-blast-close-05" },
                { "3365" , "fx-orange-double-blast-close-06" },
                { "3366" , "fx-orange-double-blast-close-07" },
                { "3367" , "fx-orange-double-blast-close-08" },
                { "3368" , "fx-orange-double-blast-close-09" },
                { "3369" , "fx-orange-double-blast-close-10" },
                { "3370" , "fx-orange-double-blast-close-11" },
                { "3371" , "fx-orange-double-blast-close-12" },
                { "3372" , "fx-orange-double-blast-close-13" },
                { "3373" , "fx-orange-double-blast-close-14" },
                { "3374" , "fx-orange-double-blast-close-15" },
                { "3375" , "fx-orange-double-blast-close-16" },
                { "3500" , "fx-red-shield-far" },
                { "3510" , "fx-red-shield-medium" },
                { "3520" , "fx-red-shield-close-1" },
                { "3521" , "fx-red-shield-close-2" },
                { "3522" , "fx-red-shield-close-3" },
                { "3523" , "fx-red-shield-close-4" },
                { "3524" , "fx-red-shield-close-5" },
                { "3525" , "fx-red-shield-close-6" },
                { "3526" , "fx-red-shield-close-7" },
                { "3527" , "fx-red-shield-close-8" },
                { "3600" , "fx-blue-shield-far" },
                { "3610" , "fx-blue-shield-medium" },
                { "3620" , "fx-blue-shield-close-1" },
                { "3621" , "fx-blue-shield-close-2" },
                { "3622" , "fx-blue-shield-close-3" },
                { "3623" , "fx-blue-shield-close-4" },
                { "3624" , "fx-blue-shield-close-5" },
                { "3625" , "fx-blue-shield-close-6" },
                { "3626" , "fx-blue-shield-close-7" },
                { "3627" , "fx-blue-shield-close-8" },
                // fighters
                { "4000" , "fighter-alliance-x-wing-red-close" },
                { "4001" , "fighter-alliance-x-wing-blue-close" },
                { "4002" , "fighter-alliance-x-wing-green-close" },
                { "4003" , "fighter-alliance-x-wing-gold-close" },
                { "4004" , "fighter-alliance-x-wing-gray-close" },
                { "4005" , "fighter-alliance-x-wing-red-far" },
                { "4006" , "fighter-alliance-x-wing-blue-far" },
                { "4007" , "fighter-alliance-x-wing-gold-far" },
                { "4008" , "fighter-alliance-x-wing-green-far" },
                { "4009" , "fighter-alliance-x-wing-gray-far" },
                { "4010" , "fighter-alliance-y-wing-red-close" },
                { "4011" , "fighter-alliance-y-wing-blue-close" },
                { "4012" , "fighter-alliance-y-wing-green-close" },
                { "4013" , "fighter-alliance-y-wing-gold-close" },
                { "4014" , "fighter-alliance-y-wing-gray-close" },
                { "4015" , "fighter-alliance-y-wing-red-far" },
                { "4016" , "fighter-alliance-y-wing-blue-far" },
                { "4017" , "fighter-alliance-y-wing-green-far" },
                { "4018" , "fighter-alliance-y-wing-gold-far" },
                { "4019" , "fighter-alliance-y-wing-gray-far" },
                { "4020" , "fighter-alliance-a-wing-red-close" },
                { "4021" , "fighter-alliance-a-wing-blue-close" },
                { "4022" , "fighter-alliance-a-wing-green-close" },
                { "4023" , "fighter-alliance-a-wing-gold-close" },
                { "4024" , "fighter-alliance-a-wing-gray-close" },
                { "4025" , "fighter-alliance-a-wing-red-far" },
                { "4026" , "fighter-alliance-a-wing-blue-far" },
                { "4027" , "fighter-alliance-a-wing-green-far" },
                { "4028" , "fighter-alliance-a-wing-gold-far" },
                { "4029" , "fighter-alliance-a-wing-gray-far" },
                { "4030" , "fighter-alliance-b-wing-red-close" },
                { "4031" , "fighter-alliance-b-wing-blue-close" },
                { "4032" , "fighter-alliance-b-wing-green-close" },
                { "4033" , "fighter-alliance-b-wing-gold-close" },
                { "4034" , "fighter-alliance-b-wing-gray-close" },
                { "4035" , "fighter-alliance-b-wing-red-far" },
                { "4036" , "fighter-alliance-b-wing-blue-far" },
                { "4037" , "fighter-alliance-b-wing-green-far" },
                { "4038" , "fighter-alliance-b-wing-gold-far" },
                { "4039" , "fighter-alliance-b-wing-gray-far" },
                { "4044" , "fighter-alliance-millenium-falcon-close" },
                { "4049" , "fighter-alliance-millenium-falcon-far" },
                { "4100" , "fighter-empire-tie-fighter-red-close" },
                { "4101" , "fighter-empire-tie-fighter-blue-close" },
                { "4102" , "fighter-empire-tie-fighter-green-close" },
                { "4103" , "fighter-empire-tie-fighter-gold-close" },
                { "4104" , "fighter-empire-tie-fighter-gray-close" },
                { "4105" , "fighter-empire-tie-fighter-red-far" },
                { "4106" , "fighter-empire-tie-fighter-blue-far" },
                { "4107" , "fighter-empire-tie-fighter-green-far" },
                { "4108" , "fighter-empire-tie-fighter-gold-far" },
                { "4109" , "fighter-empire-tie-fighter-gray-far" },
                { "4110" , "fighter-empire-tie-interceptor-red-close" },
                { "4111" , "fighter-empire-tie-interceptor-blue-close" },
                { "4112" , "fighter-empire-tie-interceptor-green-close" },
                { "4113" , "fighter-empire-tie-interceptor-gold-close" },
                { "4114" , "fighter-empire-tie-interceptor-gray-close" },
                { "4115" , "fighter-empire-tie-interceptor-red-far" },
                { "4116" , "fighter-empire-tie-interceptor-blue-far" },
                { "4117" , "fighter-empire-tie-interceptor-green-far" },
                { "4118" , "fighter-empire-tie-interceptor-gold-far" },
                { "4119" , "fighter-empire-tie-interceptor-gray-far" },
                { "4120" , "fighter-empire-tie-bomber-red-close" },
                { "4121" , "fighter-empire-tie-bomber-blue-close" },
                { "4122" , "fighter-empire-tie-bomber-green-close" },
                { "4123" , "fighter-empire-tie-bomber-gold-close" },
                { "4124" , "fighter-empire-tie-bomber-gray-close" },
                { "4125" , "fighter-empire-tie-bomber-red-far" },
                { "4126" , "fighter-empire-tie-bomber-blue-far" },
                { "4127" , "fighter-empire-tie-bomber-green-far" },
                { "4128" , "fighter-empire-tie-bomber-gold-far" },
                { "4129" , "fighter-empire-tie-bomber-gray-far" },
                { "4130" , "fighter-empire-tie-defender-red-close" },
                { "4131" , "fighter-empire-tie-defender-blue-close" },
                { "4132" , "fighter-empire-tie-defender-green-close" },
                { "4133" , "fighter-empire-tie-defender-gold-close" },
                { "4134" , "fighter-empire-tie-defender-gray-close" },
                { "4135" , "fighter-empire-tie-defender-red-far" },
                { "4136" , "fighter-empire-tie-defender-blue-far" },
                { "4137" , "fighter-empire-tie-defender-green-far" },
                { "4138" , "fighter-empire-tie-defender-gold-far" },
                { "4139" , "fighter-empire-tie-defender-gray-far" },
                // ui
                { "4200" , "ui-red-black-2x2" },
                { "4201" , "ui-blue-black-2x2" },
                { "4202" , "ui-green-black-2x2" },
                { "4203" , "ui-yellow-black-2x2" },
                { "4204" , "ui-gray-black-2x2" },
                // ships
                { "5010" , "ship-empire-death-star-completed" },
                { "5020" , "ship-empire-death-star-under-construction" },
                { "5030" , "ship-empire-death-star-empty" },
                // systems (base game)
                { "5501" , "system-01-blue-green" },
                { "5502" , "system-02-dark-green-blue" },
                { "5503" , "system-03-dark-green-blue" },
                { "5504" , "system-04-blue-green" },
                { "5505" , "system-05-blue-brown" },
                { "5506" , "system-06-green-blue" },
                { "5507" , "system-07-blue" },
                { "5508" , "system-08-rock" },
                { "5509" , "system-09-yellow" },
                { "5510" , "system-10-green-blue" },
                { "5511" , "system-11-blue-green" },
                { "5512" , "system-12-green-blue" },
                { "5513" , "system-13-dark-green-blue" },
                { "5514" , "system-14-dark-green" },
                { "5515" , "system-15-orange" },
                { "5516" , "system-16-asteroid" },
                { "5517" , "system-17-brown-blue" },
                { "5518" , "system-18-white" },
                { "5519" , "system-19-blue-green" },
                { "5520" , "system-20-dark-green-blue" },
                { "5521" , "system-21-yellow-ring" },
                { "5522" , "system-22-brown" },
                { "5523" , "system-23-purple-gray" },
                { "5524" , "system-24-red" },
                { "5525" , "system-25-blue-white" },
                { "5526" , "system-26-green-blue" },
                { "5527" , "system-exploded" },
                // systems palettes (base game)
                { "5531" , "system-01-blue-green" },
                { "5532" , "system-02-dark-green-blue" },
                { "5533" , "system-03-dark-green-blue" },
                { "5534" , "system-04-blue-green" },
                { "5535" , "system-05-blue-brown" },
                { "5536" , "system-06-green-blue" },
                { "5537" , "system-07-blue" },
                { "5538" , "system-08-rock" },
                { "5539" , "system-09-yellow" },
                { "5540" , "system-10-green-blue" },
                { "5541" , "system-11-blue-green" },
                { "5542" , "system-12-green-blue" },
                { "5543" , "system-13-dark-green-blue" },
                { "5544" , "system-14-dark-green" },
                { "5545" , "system-15-orange" },
                { "5546" , "system-16-asteroid" },
                { "5547" , "system-17-brown-blue" },
                { "5548" , "system-18-white" },
                { "5549" , "system-19-blue-green" },
                { "5550" , "system-20-dark-green-blue" },
                { "5551" , "system-21-yellow-ring" },
                { "5552" , "system-22-brown" },
                { "5553" , "system-23-purple-gray" },
                { "5554" , "system-24-red" },
                { "5555" , "system-25-blue-white" },
                { "5556" , "system-26-green-blue" },
                { "5557" , "system-exploded" },
                // systems (25th anniv patch)
                { "14001", "system-abregado-rae" },
                { "14002", "system-agamar" },
                { "14003", "system-ahch-to" },
                { "14004", "system-ajan-kloss-(moon)" },
                { "14005", "system-anaxes" },
                { "14006", "system-anoat-(atlas)" },
                { "14007", "system-ansion-(atlas)" },
                { "14008", "system-bakura-(atlas)" },
                { "14009", "system-balmorra" },
                { "14010", "system-belderone" },
                { "14011", "system-belsavis" },
                { "14012", "system-bescane" },
                { "14013", "system-bespin-(gas-giant)-(atlas)" },
                { "14014", "system-bestine-(atlas)" },
                { "14015", "system-bith" },
                { "14016", "system-bonadan-(atlas)" },
                { "14017", "system-boonta" },
                { "14018", "system-borosk" },
                { "14019", "system-bothawui-(atlas)" },
                { "14020", "system-boz-pity-(atlas)" },
                { "14021", "system-brentaal-iv-(atlas)" },
                { "14022", "system-byss-(atlas)" },
                { "14023", "system-cantonica" },
                { "14024", "system-carida" },
                { "14025", "system-cato-neimoidia" },
                { "14026", "system-celanon" },
                { "14027", "system-chandrila" },
                { "14028", "system-chardaan" },
                { "14029", "system-christophsis-(atlas)" },
                { "14030", "system-circumtore" },
                { "14031", "system-commenor" },
                { "14032", "system-concord-dawn" },
                { "14033", "system-corellia-(atlas)" },
                { "14034", "system-corsin" },
                { "14035", "system-coruscant" },
                { "14036", "system-crait" },
                { "14037", "system-csilla-(atlas)" },
                { "14038", "system-cyphar" },
                { "14039", "system-daalang" },
                { "14040", "system-dagobah-(atlas)" },
                { "14041", "system-dantooine-(atlas)" },
                { "14042", "system-dathomir-(atlas)" },
                { "14043", "system-delaya-(alderaan)" },
                { "14044", "system-dellalt" },
                { "14045", "system-dennogra" },
                { "14046", "system-denon" },
                { "14047", "system-devaron" },
                { "14048", "system-dolla" },
                { "14049", "system-d'qar" },
                { "14050", "system-dromund-kaas" },
                { "14051", "system-dubrillion" },
                { "14052", "system-duro-(atlas)" },
                { "14053", "system-eadu" },
                { "14054", "system-earth" },
                { "14055", "system-empress-teta" },
                { "14056", "system-endor-(moon)-(atlas)" },
                { "14057", "system-eriadu-(atlas)" },
                { "14058", "system-esseles" },
                { "14059", "system-exegol" },
                { "14060", "system-exodeen" },
                { "14061", "system-farstine" },
                { "14062", "system-felucia-(atlas)" },
                { "14063", "system-florn" },
                { "14064", "system-fondor-(atlas)" },
                { "14065", "system-formos" },
                { "14066", "system-gamor" },
                { "14067", "system-gamorr-(atlas)" },
                { "14068", "system-geonosis-(atlas)" },
                { "14069", "system-gerrenthum" },
                { "14070", "system-ghorman" },
                { "14071", "system-glee-anselm" },
                { "14072", "system-hapes-(atlas)" },
                { "14073", "system-honoghr-(atlas)" },
                { "14074", "system-hosnian-prime" },
                { "14075", "system-hoth-(atlas)" },
                { "14076", "system-iego-(atlas)" },
                { "14077", "system-ilum" },
                { "14078", "system-iridonia" },
                { "14079", "system-isde-naha" },
                { "14080", "system-ithor-(atlas)" },
                { "14081", "system-jaemus" },
                { "14082", "system-jakku" },
                { "14083", "system-jedha-(moon)" },
                { "14084", "system-kabal" },
                { "14085", "system-kalee-(atlas)" },
                { "14086", "system-kaller" },
                { "14087", "system-kamino-(atlas)" },
                { "14088", "system-karfeddion" },
                { "14089", "system-kashyyyk-(atlas)" },
                { "14090", "system-kef-bir-(moon)" },
                { "14091", "system-keitum" },
                { "14092", "system-kessel" },
                { "14093", "system-kimiji" },
                { "14094", "system-kuat-(atlas)" },
                { "14095", "system-lah'mu" },
                { "14096", "system-lok" },
                { "14097", "system-lothal" },
                { "14098", "system-lotho-minor" },
                { "14099", "system-lutrillia" },
                { "14100", "system-lwhekk" },
                { "14101", "system-makeb" },
                { "14102", "system-malastare-(atlas)" },
                { "14103", "system-manaan" },
                { "14104", "system-mandalore-(atlas)" },
                { "14105", "system-maridun" },
                { "14106", "system-milagro" },
                { "14107", "system-mimban-(circarpous-v)" },
                { "14108", "system-mirial" },
                { "14109", "system-mon-calamari-(atlas)" },
                { "14110", "system-mon-gazza" },
                { "14111", "system-moraband-(korriban)-(atlas)" },
                { "14112", "system-mortis" },
                { "14113", "system-mustafar-(atlas)" },
                { "14114", "system-muunilinst" },
                { "14115", "system-mygeeto-(atlas)" },
                { "14116", "system-naboo-(atlas)" },
                { "14117", "system-nagi-(atlas)" },
                { "14118", "system-nal-hutta-(atlas)" },
                { "14119", "system-nar-shaddaa-(moon)-(atlas)" },
                { "14120", "system-neimoidia-(atlas)" },
                { "14121", "system-nelvaan" },
                { "14122", "system-nevarro" },
                { "14123", "system-nexus-ortai" },
                { "14124", "system-nubia-(atlas)" },
                { "14125", "system-n'zoth-(atlas)" },
                { "14126", "system-onderon-(atlas)" },
                { "14127", "system-ord-mantel-(atlas)" },
                { "14128", "system-ord-trasi" },
                { "14129", "system-ossus-(atlas)" },
                { "14130", "system-pakuuni" },
                { "14131", "system-palanhi" },
                { "14132", "system-parnassos" },
                { "14133", "system-pasaana" },
                { "14134", "system-pax" },
                { "14135", "system-polis-massa" },
                { "14136", "system-quarzite" },
                { "14137", "system-quermia" },
                { "14138", "system-quesh" },
                { "14139", "system-rakata-prime-(lehon)-(atlas)" },
                { "14140", "system-randon" },
                { "14141", "system-rattatak-(atlas)" },
                { "14142", "system-raxus-prime-(atlas)" },
                { "14143", "system-rhen-var-(atlas)" },
                { "14144", "system-rishi-(atlas)" },
                { "14145", "system-rodia-(atlas)" },
                { "14146", "system-ruusan-(atlas)" },
                { "14147", "system-ryloth-(atlas)" },
                { "14148", "system-saleucami-(atlas)" },
                { "14149", "system-savareen" },
                { "14150", "system-scarif" },
                { "14151", "system-sernpidal-(atlas)" },
                { "14152", "system-shadda-bi-boran-(atlas)" },
                { "14153", "system-shili" },
                { "14154", "system-sissubo" },
                { "14155", "system-skako-minor" },
                { "14156", "system-sleheyron" },
                { "14157", "system-sluis-van" },
                { "14158", "system-smuggler's-run" },
                { "14159", "system-socorro" },
                { "14160", "system-sorgan" },
                { "14161", "system-sriluur" },
                { "14162", "system-sullust" },
                { "14163", "system-sy-myrth" },
                { "14164", "system-taanab-(atlas)" },
                { "14165", "system-takodana" },
                { "14166", "system-talus" },
                { "14167", "system-taris" },
                { "14168", "system-tatooine" },
                { "14169", "system-telos-iv" },
                { "14170", "system-tepasi" },
                { "14171", "system-terminus" },
                { "14172", "system-teth-(atlas)" },
                { "14173", "system-the-redoubt-(brask-oto)" },
                { "14174", "system-thyferra-(atlas)" },
                { "14175", "system-tirahnn" },
                { "14176", "system-toydaria-(atlas)" },
                { "14177", "system-tralus" },
                { "14178", "system-trandosha" },
                { "14179", "system-trask-(moon)" },
                { "14180", "system-triton-(atlas)" },
                { "14181", "system-tund-(atlas)" },
                { "14182", "system-tython" },
                { "14183", "system-umbara" },
                { "14184", "system-utapau-(atlas)" },
                { "14185", "system-vandor" },
                { "14186", "system-vinsoth" },
                { "14187", "system-voss" },
                { "14188", "system-wellspring-of-life" },
                { "14189", "system-wobani" },
                { "14190", "system-word-tandell" },
                { "14191", "system-wroona-(moon)" },
                { "14192", "system-yaga-minor" },
                { "14193", "system-yag'dhul" },
                { "14194", "system-yavin-4-(moon)-(atlas)" },
                { "14195", "system-yavin-prime-(gas-giant)" },
                { "14196", "system-zakuul" },
                { "14197", "system-zeltros" },
                { "14198", "system-ziost" },
                { "14199", "system-zonama-sekot-(atlas)" },
                { "14200", "system-zygerria" },
                // systems palettes (25th anniv patch)
                { "15001", "system-abregado-rae" },
                { "15002", "system-agamar" },
                { "15003", "system-ahch-to" },
                { "15004", "system-ajan-kloss-(moon)" },
                { "15005", "system-anaxes" },
                { "15006", "system-anoat-(atlas)" },
                { "15007", "system-ansion-(atlas)" },
                { "15008", "system-bakura-(atlas)" },
                { "15009", "system-balmorra" },
                { "15010", "system-belderone" },
                { "15011", "system-belsavis" },
                { "15012", "system-bescane" },
                { "15013", "system-bespin-(gas-giant)-(atlas)" },
                { "15014", "system-bestine-(atlas)" },
                { "15015", "system-bith" },
                { "15016", "system-bonadan-(atlas)" },
                { "15017", "system-boonta" },
                { "15018", "system-borosk" },
                { "15019", "system-bothawui-(atlas)" },
                { "15020", "system-boz-pity-(atlas)" },
                { "15021", "system-brentaal-iv-(atlas)" },
                { "15022", "system-byss-(atlas)" },
                { "15023", "system-cantonica" },
                { "15024", "system-carida" },
                { "15025", "system-cato-neimoidia" },
                { "15026", "system-celanon" },
                { "15027", "system-chandrila" },
                { "15028", "system-chardaan" },
                { "15029", "system-christophsis-(atlas)" },
                { "15030", "system-circumtore" },
                { "15031", "system-commenor" },
                { "15032", "system-concord-dawn" },
                { "15033", "system-corellia-(atlas)" },
                { "15034", "system-corsin" },
                { "15035", "system-coruscant" },
                { "15036", "system-crait" },
                { "15037", "system-csilla-(atlas)" },
                { "15038", "system-cyphar" },
                { "15039", "system-daalang" },
                { "15040", "system-dagobah-(atlas)" },
                { "15041", "system-dantooine-(atlas)" },
                { "15042", "system-dathomir-(atlas)" },
                { "15043", "system-delaya-(alderaan)" },
                { "15044", "system-dellalt" },
                { "15045", "system-dennogra" },
                { "15046", "system-denon" },
                { "15047", "system-devaron" },
                { "15048", "system-dolla" },
                { "15049", "system-d'qar" },
                { "15050", "system-dromund-kaas" },
                { "15051", "system-dubrillion" },
                { "15052", "system-duro-(atlas)" },
                { "15053", "system-eadu" },
                { "15054", "system-earth" },
                { "15055", "system-empress-teta" },
                { "15056", "system-endor-(moon)-(atlas)" },
                { "15057", "system-eriadu-(atlas)" },
                { "15058", "system-esseles" },
                { "15059", "system-exegol" },
                { "15060", "system-exodeen" },
                { "15061", "system-farstine" },
                { "15062", "system-felucia-(atlas)" },
                { "15063", "system-florn" },
                { "15064", "system-fondor-(atlas)" },
                { "15065", "system-formos" },
                { "15066", "system-gamor" },
                { "15067", "system-gamorr-(atlas)" },
                { "15068", "system-geonosis-(atlas)" },
                { "15069", "system-gerrenthum" },
                { "15070", "system-ghorman" },
                { "15071", "system-glee-anselm" },
                { "15072", "system-hapes-(atlas)" },
                { "15073", "system-honoghr-(atlas)" },
                { "15074", "system-hosnian-prime" },
                { "15075", "system-hoth-(atlas)" },
                { "15076", "system-iego-(atlas)" },
                { "15077", "system-ilum" },
                { "15078", "system-iridonia" },
                { "15079", "system-isde-naha" },
                { "15080", "system-ithor-(atlas)" },
                { "15081", "system-jaemus" },
                { "15082", "system-jakku" },
                { "15083", "system-jedha-(moon)" },
                { "15084", "system-kabal" },
                { "15085", "system-kalee-(atlas)" },
                { "15086", "system-kaller" },
                { "15087", "system-kamino-(atlas)" },
                { "15088", "system-karfeddion" },
                { "15089", "system-kashyyyk-(atlas)" },
                { "15090", "system-kef-bir-(moon)" },
                { "15091", "system-keitum" },
                { "15092", "system-kessel" },
                { "15093", "system-kimiji" },
                { "15094", "system-kuat-(atlas)" },
                { "15095", "system-lah'mu" },
                { "15096", "system-lok" },
                { "15097", "system-lothal" },
                { "15098", "system-lotho-minor" },
                { "15099", "system-lutrillia" },
                { "15100", "system-lwhekk" },
                { "15101", "system-makeb" },
                { "15102", "system-malastare-(atlas)" },
                { "15103", "system-manaan" },
                { "15104", "system-mandalore-(atlas)" },
                { "15105", "system-maridun" },
                { "15106", "system-milagro" },
                { "15107", "system-mimban-(circarpous-v)" },
                { "15108", "system-mirial" },
                { "15109", "system-mon-calamari-(atlas)" },
                { "15110", "system-mon-gazza" },
                { "15111", "system-moraband-(korriban)-(atlas)" },
                { "15112", "system-mortis" },
                { "15113", "system-mustafar-(atlas)" },
                { "15114", "system-muunilinst" },
                { "15115", "system-mygeeto-(atlas)" },
                { "15116", "system-naboo-(atlas)" },
                { "15117", "system-nagi-(atlas)" },
                { "15118", "system-nal-hutta-(atlas)" },
                { "15119", "system-nar-shaddaa-(moon)-(atlas)" },
                { "15120", "system-neimoidia-(atlas)" },
                { "15121", "system-nelvaan" },
                { "15122", "system-nevarro" },
                { "15123", "system-nexus-ortai" },
                { "15124", "system-nubia-(atlas)" },
                { "15125", "system-n'zoth-(atlas)" },
                { "15126", "system-onderon-(atlas)" },
                { "15127", "system-ord-mantel-(atlas)" },
                { "15128", "system-ord-trasi" },
                { "15129", "system-ossus-(atlas)" },
                { "15130", "system-pakuuni" },
                { "15131", "system-palanhi" },
                { "15132", "system-parnassos" },
                { "15133", "system-pasaana" },
                { "15134", "system-pax" },
                { "15135", "system-polis-massa" },
                { "15136", "system-quarzite" },
                { "15137", "system-quermia" },
                { "15138", "system-quesh" },
                { "15139", "system-rakata-prime-(lehon)-(atlas)" },
                { "15140", "system-randon" },
                { "15141", "system-rattatak-(atlas)" },
                { "15142", "system-raxus-prime-(atlas)" },
                { "15143", "system-rhen-var-(atlas)" },
                { "15144", "system-rishi-(atlas)" },
                { "15145", "system-rodia-(atlas)" },
                { "15146", "system-ruusan-(atlas)" },
                { "15147", "system-ryloth-(atlas)" },
                { "15148", "system-saleucami-(atlas)" },
                { "15149", "system-savareen" },
                { "15150", "system-scarif" },
                { "15151", "system-sernpidal-(atlas)" },
                { "15152", "system-shadda-bi-boran-(atlas)" },
                { "15153", "system-shili" },
                { "15154", "system-sissubo" },
                { "15155", "system-skako-minor" },
                { "15156", "system-sleheyron" },
                { "15157", "system-sluis-van" },
                { "15158", "system-smuggler's-run" },
                { "15159", "system-socorro" },
                { "15160", "system-sorgan" },
                { "15161", "system-sriluur" },
                { "15162", "system-sullust" },
                { "15163", "system-sy-myrth" },
                { "15164", "system-taanab-(atlas)" },
                { "15165", "system-takodana" },
                { "15166", "system-talus" },
                { "15167", "system-taris" },
                { "15168", "system-tatooine" },
                { "15169", "system-telos-iv" },
                { "15170", "system-tepasi" },
                { "15171", "system-terminus" },
                { "15172", "system-teth-(atlas)" },
                { "15173", "system-the-redoubt-(brask-oto)" },
                { "15174", "system-thyferra-(atlas)" },
                { "15175", "system-tirahnn" },
                { "15176", "system-toydaria-(atlas)" },
                { "15177", "system-tralus" },
                { "15178", "system-trandosha" },
                { "15179", "system-trask-(moon)" },
                { "15180", "system-triton-(atlas)" },
                { "15181", "system-tund-(atlas)" },
                { "15182", "system-tython" },
                { "15183", "system-umbara" },
                { "15184", "system-utapau-(atlas)" },
                { "15185", "system-vandor" },
                { "15186", "system-vinsoth" },
                { "15187", "system-voss" },
                { "15188", "system-wellspring-of-life" },
                { "15189", "system-wobani" },
                { "15190", "system-word-tandell" },
                { "15191", "system-wroona-(moon)" },
                { "15192", "system-yaga-minor" },
                { "15193", "system-yag'dhul" },
                { "15194", "system-yavin-4-(moon)-(atlas)" },
                { "15195", "system-yavin-prime-(gas-giant)" },
                { "15196", "system-zakuul" },
                { "15197", "system-zeltros" },
                { "15198", "system-ziost" },
                { "15199", "system-zonama-sekot-(atlas)" },
                { "15200", "system-zygerria" },
                // ships (base game)
                { "ASSFRG52.BMP", "ship-alliance-assault-frigate-close" },
                { "ASSFRG_M.BMP", "ship-alliance-assault-frigate-medium" },
                { "ATMAP.BMP"   , "ship-empire-assault-transport-close" },
                { "ATMAP_M.BMP" , "ship-empire-assault-transport-medium" },
                { "A_ESCR.BMP"  , "ship-alliance-alliance-escort-carrier-close" },
                { "A_ESCR_M.BMP", "ship-alliance-alliance-escort-carrier-medium" },
                { "BCRSER52.BMP", "ship-alliance-bulk-cruiser-close" },
                { "BCRSER_M.BMP", "ship-alliance-bulk-cruiser-mediu" },
                { "BULK52.BMP"  , "ship-alliance-bulk-transport-close" },
                { "BULK_M.BMP"  , "ship-alliance-bulk-transport-medium" },
                { "CARRAK52.BMP", "ship-empire-carrack-light-cruiser-close" },
                { "CARRAK_M.BMP", "ship-empire-carrack-light-cruiser-medium" },
                { "CORVET52.BMP", "ship-alliance-correlian-corvette-close" },
                { "CORVET_M.BMP", "ship-alliance-correlian-corvette-medium" },
                { "ESCARRIM.BMP", "ship-empire-imperial-escort-carrier-medium" },
                { "ESCARR_I.BMP", "ship-empire-imperial-escort-carrier-close" },
                { "E_DRED52.BMP", "ship-empire-imperial-dreadnaught-close" },
                { "E_DRED_M.BMP", "ship-empire-imperial-dreadnaught-medium" },
                { "GLMAP128.BMP", "ship-empire-galleon-close" },
                { "GLMAP_M.BMP" , "ship-empire-galleon-medium" },
                { "GUNSHIP.BMP" , "ship-alliance-correlian-gunship-close" },
                { "GUNSHP_M.BMP", "ship-alliance-correlian-gunship-medium" },
                { "INTERD.BMP"  , "ship-empire-interdictor-cruiser-close" },
                { "INTERD_M.BMP", "ship-empire-interdictor-cruiser-medium" },
                { "LANCER52.BMP", "ship-empire-lancer-frigate-close" },
                { "LANCER_M.BMP", "ship-empire-lancer-frigate-medium" },
                { "MONCAL52.BMP", "ship-alliance-mon-calamari-cruiser-close" },
                { "MONCAL_M.BMP", "ship-alliance-mon-calamari-cruiser-medium" },
                { "NEBUL52.BMP" , "ship-alliance-nebulon-b-frigate-close" },
                { "NEBUL_M.BMP" , "ship-alliance-nebulon-b-frigate-medium" },
                { "R1MAP.BMP"   , "ship-alliance-cc-7700-frigate-close" },
                { "R1MAP_M.BMP" , "ship-alliance-cc-7700-frigate-medium" },
                { "R2MAP.BMP"   , "ship-alliance-bulwark-battlecruiser-close" },
                { "R2MAP_M.BMP" , "ship-alliance-bulwark-battlecruiser-medium" },
                { "R3MAP2.BMP"  , "ship-alliance-cc-9600-frigate-close" },
                { "R3MAP2_M.BMP", "ship-alliance-cc-9600-frigate-medium" },
                { "R4MAP.BMP"   , "ship-alliance-liberator-cruiser-close" },
                { "R4MAP_M.BMP" , "ship-alliance-liberator-cruiser-medium" },
                { "R5MAP.BMP"   , "ship-alliance-dauntless-cruiser-close" },
                { "R5MAP_M.BMP" , "ship-alliance-dauntless-cruiser-medium" },
                { "R_DRED52.BMP", "ship-alliance-alliance-dreadnaught-close" },
                { "R_DRED_M.BMP", "ship-alliance-alliance-dreadnaught-medium" },
                { "SDESTI52.BMP", "ship-empire-imperial-star-destroyer-close" },
                { "SDESTI_M.BMP", "ship-empire-imperial-star-destroyer-medium" },
                { "SDESTV52.BMP", "ship-empire-victory-destroyer-close" },
                { "SDESTV_M.BMP", "ship-empire-victory-destroyer-medium" },
                { "SDSTI252.BMP", "ship-empire-imperial-2-star-destroyer-close" },
                { "SDSTI2_M.BMP", "ship-empire-imperial-2-star-destroyer-medium" },
                { "SDSTV252.BMP", "ship-empire-victory-2-star-destroyer-close" },
                { "SDSTV2_M.BMP", "ship-empire-victory-2-star-destroyer-medium" },
                { "SPDEST24.BMP", "ship-empire-super-star-destroyer-medium" },
                { "SPDEST52.BMP", "ship-empire-super-star-destroyer-close" },
                { "SPDEST_S.BMP", "ship-empire-super-star-destroyer-far" },
                { "STRGAL.BMP"  , "ship-empire-star-galleon-close" },
                { "STRGAL_M.BMP", "ship-empire-star-galleon-medium" },
                { "STRIKE52.BMP", "ship-empire-strike-cruiser-close" },
                { "STRIKE_M.BMP", "ship-empire-strike-cruiser-medium" },
                { "TUNA52.BMP"  , "ship-alliance-medium-transport-close" },
                { "TUNA_M.BMP"  , "ship-alliance-medium-transport-medium" },
            };
        NamesBitmap = new Dictionary<string, string>
            {
                // ui
                { "1000", "ui-control-panel" },
                { "1001", "ui-task-forces-alliance" },
                { "1004", "ui-task-forces-empire" },
                { "1005", "ui-task-force-button-unpressed" },
                { "1006", "ui-task-force-button-pressed" },
                { "1007", "ui-task-force-button-unassigned" },
                { "1008", "ui-fighter-squadrons-alliance" },
                { "1010", "ui-fighter-squadrons-empire" },
                { "1012", "ui-red-squadron-button-unpressed" },
                { "1013", "ui-blue-squadron-button-unpressed" },
                { "1014", "ui-green-squadron-button-unpressed" },
                { "1015", "ui-gold-squadron-button-unpressed" },
                { "1016", "ui-red-squadron-button-pressed" },
                { "1017", "ui-blue-squadron-button-pressed" },
                { "1018", "ui-green-squadron-button-pressed" },
                { "1019", "ui-gold-squadron-button-pressed" },
                { "1020", "ui-squadron-unassigned" },
                { "1021", "ui-death-star-laser-ready" },
                { "1022", "ui-death-star-laser-fired" },
                { "1023", "ui-death star-laser-loading" },
                { "1024", "ui-death-star-laser-gauge" },
                { "1026", "ui-navigation-point-set-1-unpressed" },
                { "1027", "ui-navigation-point-set-2-unpressed" },
                { "1028", "ui-navigation-point-set-3-unpressed" },
                { "1029", "ui-navigation-point-set-4-unpressed" },
                { "1030", "ui-navigation-point-set-1-pressed" },
                { "1031", "ui-navigation-point-set-2-pressed" },
                { "1032", "ui-navigation-point-set-3-pressed" },
                { "1033", "ui-navigation-point-set-4-pressed" },
                { "1034", "ui-highlight-alliance-ships" },
                { "1035", "ui-dim-alliance-ships" },
                { "1036", "ui-highlight-empire-ships" },
                { "1037", "ui-dim-empire-ships" },
                { "1038", "ui-game-options-unpressed" },
                { "1039", "ui-game-options-pressed" },
                { "1040", "ui-remember-camera-position-unpressed" },
                { "1041", "ui-remember-camera-position-pressed" },
                { "1042", "ui-reset-camera-view-unpressed" },
                { "1043", "ui-reset-camera-view-pressed" },
                { "1044", "ui-zoom-in-unpressed" },
                { "1045", "ui-zoom-in-pressed" },
                { "1046", "ui-zoom-out-unpressed" },
                { "1047", "ui-zoom-out-pressed" },
                { "1048", "ui-rotate-left-unpressed" },
                { "1049", "ui-rotate-left-pressed" },
                { "1050", "ui-rotate-right-unpressed" },
                { "1051", "ui-rotate-right-pressed" },
                { "1052", "ui-tilt-up-unpressed" },
                { "1053", "ui-tilt-up-pressed" },
                { "1055", "ui-tilt-down-unpressed" },
                { "1056", "ui-tilt-down-pressed" },
                { "1058", "ui-reset-camera-subject-unpressed" },
                { "1059", "ui-reset-camera-subject-pressed" },
                { "1060", "ui-pause-battle" },
                { "1061", "ui-resume-battle" },
                { "1101", "ui-previous-capital-ship-in-task-force-unpressed" },
                { "1102", "ui-previous-capital-ship-in-task-force-pressed" },
                { "1103", "ui-next-capital-ship-in-task-force-unpressed" },
                { "1104", "ui-next-capital-ship-in-task-force-pressed" },
                { "1105", "ui-maneuvers-tactics-unpressed" },
                { "1106", "ui-maneuvers-tactics-pressed" },
                { "1107", "ui-missions-unpressed" },
                { "1108", "ui-missions-pressed" },
                { "1109", "ui-red-triangle-left" },
                { "1110", "ui-red-triangle-left" },
                { "1111", "ui-red-triangle-right" },
                { "1112", "ui-red-triangle-right" },
                { "1113", "ui-assign-maneuver-tactics-unpressed" },
                { "1114", "ui-assign-maneuver-tactics-pressed" },
                { "1115", "ui-cancel-unpressed" },
                { "1116", "ui-cancel-pressed" },
                { "1117", "ui-stand-off" },
                { "1118", "ui-surround" },
                { "1133", "ui-left-hook-unpressed" },
                { "1134", "ui-left-hook-pressed" },
                { "1135", "ui-right-hook-unpressed" },
                { "1136", "ui-right-hook-pressed" },
                { "1137", "ui-hammer-unpressed" },
                { "1138", "ui-hammer-pressed" },
                { "1139", "ui-anvil-unpressed" },
                { "1140", "ui-anvil-pressed" },
                { "1141", "ui-stop-unpressed" },
                { "1142", "ui-stop-pressed" },
                { "1149", "ui-withdraw-from-battle-unpressed" },
                { "1150", "ui-withdraw-from-battle-pressed" },
                { "1151", "ui-get-immediate-result-unpressed" },
                { "1152", "ui-get-immediate-result-pressed" },
                { "1153", "ui-take-command" },
                { "1154", "ui-observe-battle" },
                { "1155", "ui-game-options-unpressed" },
                { "1156", "ui-game-options-pressed" },
                { "1157", "ui-close-unpressed" },
                { "1158", "ui-close-pressed" },
                { "1170", "ui-recover-empire-unpressed" },
                { "1171", "ui-recover-empire-pressed" },
                { "1172", "ui-recover-empire-disabled" },
                { "1173", "ui-recover-alliance-unpressed" },
                { "1174", "ui-recover-alliance-pressed" },
                { "1175", "ui-recover-alliance-disabled" },
                { "1176", "ui-attack-death-star-unpressed" },
                { "1177", "ui-attack-death-star-pressed" },
                { "1178", "ui-attack-death-star-disabled" },
                { "1179", "ui-attack-capital-ships-alliance-unpressed" },
                { "1180", "ui-attack-capital-ships-alliance-pressed" },
                { "1182", "ui-attack-capital-ships-empire-unpressed" },
                { "1183", "ui-attack-capital-ships-empire-pressed" },
                { "1191", "ui-attack-fighters-alliance-unpressed" },
                { "1192", "ui-attack-fighters-alliance-pressed" },
                { "1194", "ui-attack-fighters-empire-unpressed" },
                { "1195", "ui-attack-fighters-empire-pressed" },
                { "1201", "ui-shield-recharge-0%" },
                { "1202", "ui-shield-recharge-25%" },
                { "1203", "ui-shield-recharge-50%" },
                { "1204", "ui-shield-recharge-75%" },
                { "1205", "ui-shield-recharge-100%" },
                { "1206", "ui-weapon-recharge-0%" },
                { "1207", "ui-weapon-recharge-25%" },
                { "1208", "ui-weapon-recharge-50%" },
                { "1209", "ui-weapon-recharge-75%" },
                { "1210", "ui-weapon-recharge-100%" },
                { "1211", "ui-tractor-beam-0%" },
                { "1212", "ui-tractor-beam-25%" },
                { "1213", "ui-tractor-beam-50%" },
                { "1214", "ui-tractor-beam-75%" },
                { "1215", "ui-tractor-beam-100%" },
                { "1216", "ui-engines-0%" },
                { "1217", "ui-engines-25%" },
                { "1218", "ui-engines-50%" },
                { "1219", "ui-engines-75%" },
                { "1220", "ui-engines-100%" },
                { "1221", "ui-hyperspace-engines-0%" },
                { "1222", "ui-hyperspace-engines-25%" },
                { "1223", "ui-hyperspace-engines-50%" },
                { "1224", "ui-hyperspace-engines-75%" },
                { "1225", "ui-hyperspace-engines-100%" },
                { "1301", "ui-hud-background" },
                { "1302", "ui-right-panel-hull-integrity-shield-strength" },
                { "1303", "ui-shutter-alliance" },
                { "1304", "ui-shutter-empire" },
                { "1305", "ui-passengers-hud" },
                { "1306", "ui-game-options-hud" },
                { "1307", "ui-fighters-squadron-hud" },
                { "1308", "ui-missions-hud" },
                { "1309", "ui-maneuvers-tactics-hud" },
                { "1310", "ui-unknown-hud" },
                { "1351", "ui-unknown-button-1-unpressed" },
                { "1352", "ui-unknown-button-1-pressed" },
                { "1353", "ui-unknown-button-2-unpressed" },
                { "1354", "ui-unknown-button-2-pressed" },
                { "1555", "ui-unknown-icon-left" },
                { "1356", "ui-unknown-icon-middle" },
                { "1357", "ui-unknown-icon-right" },
                { "1358", "ui-black-square" },
                { "1359", "ui-gray-square" },
                // ships
                { "2001", "ship-mon-calamari-cruiser" },
                { "2002", "ship-bulk-cruiser" },
                { "2003", "ship-assault-frigate" },
                { "2004", "ship-nebulon-b-frigate" },
                { "2005", "ship-alliance-escort-carrier" },
                { "2006", "ship-corellian-corvette" },
                { "2007", "ship-medium-transport" },
                { "2008", "ship-bulk-transport" },
                { "2009", "ship-corellian-gunship" },
                { "2010", "ship-alliance-dreadnaught" },
                { "2011", "ship-cc-7700-frigate" },
                { "2012", "ship-cc-9600-frigate" },
                { "2013", "ship-bulwark-battlecruiser" },
                { "2014", "ship-liberator-cruiser" },
                { "2015", "ship-dauntless-cruiser" },
                { "2016", "ship-strike-cruiser" },
                { "2017", "ship-lancer-frigate" },
                { "2018", "ship-interdictor-cruiser" },
                { "2019", "ship-carrack-light-cruiser" },
                { "2020", "ship-victory-destroyer" },
                { "2021", "ship-imperial-star-destroyer" },
                { "2022", "ship-super-star-destroyer" },
                { "2023", "ship-assault-transport" },
                { "2024", "ship-galleon" },
                { "2025", "ship-victory-ii-star-destroyer" },
                { "2026", "ship-imperial-ii-star-destroyer" },
                { "2027", "ship-star-galleon" },
                { "2028", "ship-imperial-escort-carrier" },
                { "2029", "ship-imperial-dreadnaught" },
                // fighters
                { "2030", "squadron-hud-fighter-alliance-x-wing" },
                { "2031", "squadron-hud-fighter-alliance-y-wing" },
                { "2032", "squadron-hud-fighter-alliance-a-wing" },
                { "2033", "squadron-hud-fighter-alliance-b-wing" },
                { "2034", "squadron-hud-fighter-empire-tie-fighter" },
                { "2035", "squadron-hud-fighter-empire-tie-advanced" },
                { "2036", "squadron-hud-fighter-empire-tie-bomber" },
                { "2037", "squadron-hud-fighter-empire-tie-defender" },
                // ships
                { "2038", "ship-death-star" },
                // ui
                { "2101", "ui-maneuvers-tactics-hud-left-hook" },
                { "2102", "ui-maneuvers-tactics-hud-right-hook" },
                { "2103", "ui-maneuvers-tactics-hud-hammer" },
                { "2104", "ui-maneuvers-tactics-hud-anvil" },
                { "2105", "ui-maneuvers-tactics-hud-stop" },
                { "2151", "ui-missions-hud-attack-capital-ships-alliance" },
                { "2152", "ui-missions-hud-attack-fighters-alliance" },
                { "2153", "ui-missions-hud-recover-alliance" },
                { "2154", "ui-missions-hud-attack-death-star-alliance" },
                { "2155", "ui-missions-hud-attack-capital-ships-empire" },
                { "2156", "ui-missions-hud-attack-fighters-empire" },
                { "2157", "ui-missions-hud-recover-empire" },
                { "2158", "ui-hud-empty" },
                // characters
                { "2201", "character-alliance-ackbar" },
                { "2202", "character-alliance-afyon" },
                { "2203", "character-alliance-kaiya-andrimetrum" },
                { "2204", "character-alliance-wedge-antilles" },
                { "2205", "character-alliance-lando-calrissian" },
                { "2206", "character-alliance-chewbacca" },
                { "2207", "character-empire-covell" },
                { "2208", "character-empire-daala" },
                { "2209", "character-alliance-bren-derlin" },
                { "2210", "character-alliance-jan-dodonna" },
                { "2211", "character-empire-dorja" },
                { "2212", "character-alliance-drayson" },
                { "2214", "character-empire-emperor-palpatine" },
                { "2215", "character-empire-bin-essada" },
                { "2216", "character-empire-niles-ferrier" },
                { "2217", "character-alliance-borsk-fey'lya" },
                { "2218", "character-empire-griff" },
                { "2219", "character-empire-grammel" },
                { "2220", "character-alliance-garm-bel-iblis" },
                { "2221", "character-empire-garindan" },
                { "2222", "character-empire-jerjerrod" },
                { "2223", "character-alliance-roget-jiriss" },
                { "2225", "character-alliance-talon-karrde" },
                { "2226", "character-empire-klev" },
                { "2227", "character-empire-labansat" },
                { "2228", "character-empire-bevel-lemelisk" },
                { "2229", "character-alliance-luke-knight" },
                { "2230", "character-alliance-luke-skywalker" },
                { "2231", "character-alliance-crix-madine" },
                { "2232", "character-alliance-ma'w'shiye" },
                { "2233", "character-empire-menndo" },
                { "2234", "character-alliance-mon-mothma" },
                { "2235", "character-alliance-narra" },
                { "2236", "character-empire-needa" },
                { "2237", "character-alliance-huoba-neva" },
                { "2239", "character-empire-bane-nothos" },
                { "2240", "character-empire-noval-garaint" },
                { "2241", "character-alliance-leia-organa" },
                { "2242", "character-empire-orlok" },
                { "2243", "character-alliance-orrimaarko" },
                { "2244", "character-empire-ozzel" },
                { "2245", "character-alliance-page" },
                { "2246", "character-empire-pellaeon" },
                { "2247", "character-empire-piett" },
                { "2248", "character-alliance-mazer-rackus" },
                { "2249", "character-alliance-tura-raftican" },
                { "2250", "character-alliance-carlist-rieekan" },
                { "2251", "character-empire-shenir-rix" },
                { "2253", "character-empire-screed" },
                { "2254", "character-alliance-syub-snunb" },
                { "2255", "character-alliance-han-solo" },
                { "2256", "character-alliance-adar-tallon" },
                { "2257", "character-empire-pter-thanas" },
                { "2258", "character-empire-thrawn" },
                { "2260", "character-empire-darth-vader" },
                { "2261", "character-empire-veers" },
                { "2262", "character-empire-villar" },
                { "2263", "character-alliance-sarin-virgilio" },
                { "2264", "character-alliance-vanden-willard" },
                { "2265", "character-empire-zuggs" },
                { "2266", "character-empire-brandei" },
                // troops & special forces
                { "2301", "troop-alliance-alliance-army-regiment" },
                { "2302", "special-force-alliance-bothan-spies" },
                { "2303", "special-force-empire-imperial-commandos" },
                { "2304", "special-force-empire-dark-force-regiment" },
                { "2305", "special-force-empire-imperial-espionage-droid" },
                { "2306", "troop-empire-imperial-army-regiment" },
                { "2307", "troop-empire-imperial-fleet-regiment" },
                { "2308", "special-force-alliance-guerillas" },
                { "2309", "special-force-alliance-infiltrators" },
                { "2310", "troop-alliance-alliance-fleet-regiment" },
                { "2311", "troop-alliance-mon-calamari-regiment" },
                { "2312", "troop-empire-noghri-death-commandos" },
                { "2313", "special-force-empire-imperial-probe-droid" },
                { "2314", "troop-alliance-sullustan-regiment" },
                { "2315", "troop-empire-war-droid-regiment" },
                { "2316", "troop-alliance-wookiee-regiment" },
                { "2317", "troop-empire-stormtrooper-regiment" },
                { "2318", "special-force-alliance-longprobe-y-wing-recon-team" },
                // ui
                { "DATA_BUTTON_DN_FIGHTERGROUP_RECOVER", "ui-pressed" },
                { "DATA_BUTTON_DN_FIGHTERGROUP_TACTICS", "ui-pressed" },
                { "DATA_BUTTON_UP_FIGHTERGROUP_RECOVER", "ui-unpressed" },
                { "DATA_BUTTON_UP_FIGHTERGROUP_TACTICS", "ui-unpressed" },
        };
        NamesWave = new Dictionary<string, string>
            {
                { "13000", "blast" },
                { "13001", "blast" },
                { "13002", "blast" },
                { "13003", "blast" },
                { "13004", "blast" },
                { "13005", "blast" },
                { "13006", "blast" },
                { "13007", "blast" },
                { "13008", "blast" },
                { "13009", "blast" },
                { "13010", "blast" },
                { "13011", "blast" },
                { "13012", "blast" },
                { "13013", "blast" },
                { "13014", "blast" },
                { "13015", "blast" },
                { "13016", "blast" },
                { "13017", "blast" },
                { "13018", "blast" },
                { "13019", "blast" },
                { "13020", "blast" },
                { "13021", "blast" },
                { "13022", "blast" },
                { "13023", "blast" },
                { "13024", "blast" },
                { "13025", "blast" },
                { "13026", "blast" },
                { "13027", "blast" },
                { "13028", "blast" },
                { "13029", "blast" },
                { "13030", "blast" },
                { "13031", "blast" },
                { "13032", "blast" },
                { "13033", "blast" },
                { "13034", "blast" },
                { "13035", "blast" },
                { "13036", "blast" },
                { "13037", "blast" },
                { "13038", "blast" },
                { "13039", "blast" },
                { "13040", "blast" },
                { "13041", "blast" },
                { "13042", "blast" },
                { "13043", "blast" },
                { "13044", "blast" },
                { "13045", "blast" },
                { "13046", "blast" },
                { "13047", "blast" },
                { "13048", "blast" },
                { "13049", "blast" },
                { "13050", "blast" },
                { "13051", "blast" },
                { "13052", "blast" },
                { "13053", "blast" },
                { "13054", "blast" },
                { "13055", "blast" },
                { "13056", "reactor" },
                { "13057", "reactor" },
                { "13058", "reactor" },
                { "13059", "reactor" },
                { "13060", "droid" },
                { "13061", "pass-by-fighter-empire" },
                { "13062", "pass-by-fighter-alliance" },
                { "13063", "pass-by" },
                { "13064", "pass-by" },
                { "13065", "pass-by" },
            };
    }
}
