namespace SwRebellionEditor;

// WAVE, Version Info

public class Voicefxa : ResourcesDll
{
    public Voicefxa(string fileName) : base(fileName)
    {
        NamesWave = new Dictionary<string, string>
            {
                // alliance voice messages
                { "14001", "the fleet is ready admiral, what are your orders" },
                { "14002", "orders acknowledged, beginning maneuver" },
                { "14003", "task force 1, acknowledged, beginning maneuver" },
                { "14004", "task force 2, acknowledged, beginning maneuver" },
                { "14005", "task force 3, acknowledged, beginning maneuver" },
                { "14006", "task force 4, acknowledged, beginning maneuver" },
                { "14007", "task force 5, acknowledged, beginning maneuver" },
                { "14008", "task force 6, acknowledged, beginning maneuver" },
                { "14009", "task force 7, acknowledged, beginning maneuver" },
                { "14010", "task force 8, acknowledged, beginning maneuver" },
                { "14011", "red group, acknowledged, beginning maneuver" },
                { "14012", "blue group, acknowledged, beginning maneuver" },
                { "14013", "green group, acknowledged, beginning maneuver" },
                { "14014", "gold group, acknowledged, beginning maneuver" },
                { "14015", "ship reporting, maneuver complete, engaging targets" },
                { "14016", "task force 1 reporting, maneuver complete, engaging targets" },
                { "14017", "task force 2 reporting, maneuver complete, engaging targets" },
                { "14018", "task force 3 reporting, maneuver complete, engaging targets" },
                { "14019", "task force 4 reporting, maneuver complete, engaging targets" },
                { "14020", "task force 5 reporting, maneuver complete, engaging targets" },
                { "14021", "task force 6 reporting, maneuver complete, engaging targets" },
                { "14022", "task force 7 reporting, maneuver complete, engaging targets" },
                { "14023", "task force 8 reporting, maneuver complete, engaging targets" },
                { "14024", "red group reporting, maneuver complete, engaging targets" },
                { "14025", "blue group reporting, maneuver complete, engaging targets" },
                { "14026", "green group reporting, maneuver complete, engaging targets" },
                { "14027", "gold group reporting, maneuver complete, engaging targets" },
                { "14028", "order acknowledged, beginning attack" },
                { "14029", "task force 1 acknowledged, engaging targets" },
                { "14030", "task force 2 acknowledged, engaging targets" },
                { "14031", "task force 3 acknowledged, engaging targets" },
                { "14032", "task force 4 acknowledged, engaging targets" },
                { "14033", "task force 5 acknowledged, engaging targets" },
                { "14034", "task force 6 acknowledged, engaging targets" },
                { "14035", "task force 7 acknowledged, engaging targets" },
                { "14036", "task force 8 acknowledged, engaging targets" },
                { "14037", "red group acknowledged, engaging targets" },
                { "14038", "blue group acknowledged, engaging targets" },
                { "14039", "green group acknowledged, engaging targets" },
                { "14040", "gold group acknowledged, engaging targets" },
                { "14041", "ship reporting, orders completed" },
                { "14042", "task force 1 requesting orders" },
                { "14043", "task force 2 requesting orders" },
                { "14044", "task force 3 requesting orders" },
                { "14045", "task force 4 requesting orders" },
                { "14046", "task force 5 requesting orders" },
                { "14047", "task force 6 requesting orders" },
                { "14048", "task force 7 requesting orders" },
                { "14049", "task force 8 requesting orders" },
                { "14050", "red group requesting orders" },
                { "14051", "blue group requesting orders" },
                { "14052", "green group requesting orders" },
                { "14053", "gold group requesting orders" },
                { "14054", "ship reporting, target destroyed" },
                { "14055", "task force 1 reporting, target destroyed" },
                { "14056", "task force 2 reporting, target destroyed" },
                { "14057", "task force 3 reporting, target destroyed" },
                { "14058", "task force 4 reporting, target destroyed" },
                { "14059", "task force 5 reporting, target destroyed" },
                { "14060", "task force 6 reporting, target destroyed" },
                { "14061", "task force 7 reporting, target destroyed" },
                { "14062", "task force 8 reporting, target destroyed" },
                { "14063", "red group reporting, target destroyed" },
                { "14064", "blue group reporting, target destroyed" },
                { "14065", "green group reporting, target destroyed" },
                { "14066", "gold group reporting, target destroyed" },
                { "14067", "ship destroyed, repeat ship destroyed" },
                { "14068", "task force 1 reporting they lost a ship" },
                { "14069", "task force 2 reporting they lost a ship" },
                { "14070", "task force 3 reporting they lost a ship" },
                { "14071", "task force 4 reporting they lost a ship" },
                { "14072", "task force 5 reporting they lost a ship" },
                { "14073", "task force 6 reporting they lost a ship" },
                { "14074", "task force 7 reporting they lost a ship" },
                { "14075", "task force 8 reporting they lost a ship" },
                { "14076", "red group reporting, they're taking losses" },
                { "14077", "blue group reporting, they're taking losses" },
                { "14078", "green group reporting, they're taking losses" },
                { "14079", "gold group reporting, they're taking losses" },
                { "14080", "task force 1 acknowledged, assuming formation" },
                { "14081", "task force 2 acknowledged, assuming formation" },
                { "14082", "task force 3 acknowledged, assuming formation" },
                { "14083", "task force 4 acknowledged, assuming formation" },
                { "14084", "task force 5 acknowledged, assuming formation" },
                { "14085", "task force 6 acknowledged, assuming formation" },
                { "14086", "task force 7 acknowledged, assuming formation" },
                { "14087", "task force 8 acknowledged, assuming formation" },
                { "14088", "mission assignment acknowledged" },
                { "14089", "task force 1 acknowledges mission assignment" },
                { "14090", "task force 2 acknowledges mission assignment" },
                { "14091", "task force 3 acknowledges mission assignment" },
                { "14092", "task force 4 acknowledges mission assignment" },
                { "14093", "task force 5 acknowledges mission assignment" },
                { "14094", "task force 6 acknowledges mission assignment" },
                { "14095", "task force 7 acknowledges mission assignment" },
                { "14096", "task force 8 acknowledges mission assignment" },
                { "14097", "red group acknowledges mission assignment" },
                { "14098", "blue group acknowledges mission assignment" },
                { "14099", "green group acknowledges mission assignment" },
                { "14100", "gold group acknowledges mission assignment" },
                { "14101", "command circuits are filled to capacity, no new task forces can be formed, assigned ships will assume orders individually" },
                { "14102", "personnel ejecting from fighters, we'll have to recover them after the battle" },
                { "14103", "personnel forced to abandon ship, we'll have to recover them after the battle" },
                { "14104", "red group reporting, remaining fighters recovered" },
                { "14105", "blue group reporting, remaining fighters recovered" },
                { "14106", "green group reporting, remaining fighters recovered" },
                { "14107", "gold group reporting, remaining fighters recovered" },
                { "14108", "red group reporting, they cant recover all their fighters, they're is not enough docking space on the remaining ships" },
                { "14109", "blue group reporting, they cant recover all their fighters, they're is not enough docking space on the remaining ships" },
                { "14110", "green group reporting, they cant recover all their fighters, they're is not enough docking space on the remaining ships" },
                { "14111", "gold group reporting, they cant recover all their fighters, they're is not enough docking space on the remaining ships" },
                { "14112", "all units reporting in, the fleet is preparing to make the jump into hyperspace" },
                { "14113", "stand by alert, death star approaching" },
                { "14114", "the death star is firing at us" },
                { "14115", "sensors report that we have an opening to launch an attack on the death star" },
                { "14116", "sensors have detected a death star shield generator, that means it will be impossible to attack this death star" },
                { "14117", "sensor reports indicate, there are too many imperial fighters to allow us to engage the death star, we'll have to destroy some of them" },
                { "14118", "some ships report that they cannot make the jump into hyperspace, if we withdraw they will be left behind" },
                { "14119", "the fleet is jumping into hyperspace, the withdrawl is complete" },
                { "14120", "the imperial fleet is withdrawing, we've won" },
                { "14121", "all imperial ships have been destroyed, thats it, we've won" },
                { "14122", "our fleet has been destroyed, the empire has won the battle" },
				
				// death star attack sequence/animation ?
                { "15133", "all wings report in" },
                { "15134", "accelerate to attack speed" },
                { "15135", "stay low" },
                { "15136", "the exhaust port is marked and locked in" },
                { "15137", "switch to targeting computer" },
                { "15138", "watch your back" },
                { "15139", "stabilize rear deflectors" },
                { "15140", "you've picked one up, watch it" },
                { "15141", "stay on target" },
                { "15142", "eject, eject" },
                { "15143", "my scope shows the tower, but i can't see the exhaust port" },
                { "15144", "computer's locked, getting a signal" },
                { "15145", "i can't shake him" },
                { "15146", "it's no good, i can't maneuver" },
                { "15147", "i'm hiiit" },
                { "15148", "blue group to command, breaking off to attack death star" },
                { "15149", "blue group to command, attack on death star commencing" },
                { "15150", "blue group to command, attack failed, repeat, attack failed" },
                { "15151", "blue group to command, target destroyed" },
                { "15152", "green group acknowledged, engaging death star" },
                { "15153", "green group to command, attacking now" },
                { "15154", "green group to command, attempting to break off, attack has failed" },
                { "15155", "green group to command, death star destroyed" },
                { "15156", "i'm going in, gold group attacking death star" },
                { "15157", "yeeeehaw, gold group reporting, we're going in" },
                { "15158", "blast it, this is gold group, we're out, our attack failed" },
                { "15159", "yes, gold group reporting, just call anytime" },
                { "15160", "red group closing on death star" },
                { "15161", "red group to flag, we're starting our attack run" },
                { "15162", "red group to flag, we've taken heavy losses, we can't get to the target" },
                { "15163", "red group to flag, that's how it's done" },
            };
    }
}
