namespace SwRebellionEditor;

// WAVE, Version Info

public class Voicefxe : ResourcesDll
{
    public Voicefxe(string fileName) : base(fileName)
    {
        NamesWave = new Dictionary<string, string>
        {   
            // empire voice messages
            { "15001", "the fleet is ready admiral, we await your orders" },
            { "15002", "order acknowledged, beginning maneuver" },
            { "15003", "task force 1 acknowledges, beginning maneuver" },
            { "15004", "task force 2 acknowledges, beginning maneuver" },
            { "15005", "task force 3 acknowledges, beginning maneuver" },
            { "15006", "task force 4 acknowledges, beginning maneuver" },
            { "15007", "task force 5 acknowledges, beginning maneuver" },
            { "15008", "task force 6 acknowledges, beginning maneuver" },
            { "15009", "task force 7 acknowledges, beginning maneuver" },
            { "15010", "task force 8 acknowledges, beginning maneuver" },
            { "15011", "red group acknowledges, beginning maneuver" },
            { "15012", "blue group acknowledges, beginning maneuver" },
            { "15013", "green group acknowledges, beginning maneuver" },
            { "15014", "gold group acknowledges, beginning maneuver" },
            { "15015", "ship reporting, maneuver complete, engaging targets" },
            { "15016", "task force 1 reporting, maneuver complete, engaging targets" },
            { "15017", "task force 2 reporting, maneuver complete, engaging targets" },
            { "15018", "task force 3 reporting, maneuver complete, engaging targets" },
            { "15019", "task force 4 reporting, maneuver complete, engaging targets" },
            { "15020", "task force 5 reporting, maneuver complete, engaging targets" },
            { "15021", "task force 6 reporting, maneuver complete, engaging targets" },
            { "15022", "task force 7 reporting, maneuver complete, engaging targets" },
            { "15023", "task force 8 reporting, maneuver complete, engaging targets" },
            { "15024", "red group reporting, maneuver complete, engaging targets" },
            { "15025", "blue group reporting, maneuver complete, engaging targets" },
            { "15026", "green group reporting, maneuver complete, engaging targets" },
            { "15027", "gold group reporting, maneuver complete, engaging targets" },
            { "15028", "order acknowledged, beginning attack" },
            { "15029", "task force 1 acknowledges, engaging targets" },
            { "15030", "task force 2 acknowledges, engaging targets" },
            { "15031", "task force 3 acknowledges, engaging targets" },
            { "15032", "task force 4 acknowledges, engaging targets" },
            { "15033", "task force 5 acknowledges, engaging targets" },
            { "15034", "task force 6 acknowledges, engaging targets" },
            { "15035", "task force 7 acknowledges, engaging targets" },
            { "15036", "task force 8 acknowledges, engaging targets" },
            { "15037", "red group acknowledges, engaging targets" },
            { "15038", "blue group acknowledges, engaging targets" },
            { "15039", "green group acknowledges, engaging targets" },
            { "15040", "gold group acknowledges, engaging targets" },
            { "15041", "ship reporting, orders completed" },
            { "15042", "task force 1 requesting orders" },
            { "15043", "task force 2 requesting orders" },
            { "15044", "task force 3 requesting orders" },
            { "15045", "task force 4 requesting orders" },
            { "15046", "task force 5 requesting orders" },
            { "15047", "task force 6 requesting orders" },
            { "15048", "task force 7 requesting orders" },
            { "15049", "task force 8 requesting orders" },
            { "15050", "red group, requesting orders" },
            { "15051", "blue group, requesting orders" },
            { "15052", "green group, requesting orders" },
            { "15053", "gold group, requesting orders" },
            { "15054", "ship reporting, target destroyed" },
            { "15055", "task force 1 reporting, target destroyed" },
            { "15056", "task force 2 reporting, target destroyed" },
            { "15057", "task force 3 reporting, target destroyed" },
            { "15058", "task force 4 reporting, target destroyed" },
            { "15059", "task force 5 reporting, target destroyed" },
            { "15060", "task force 6 reporting, target destroyed" },
            { "15061", "task force 7 reporting, target destroyed" },
            { "15062", "task force 8 reporting, target destroyed" },
            { "15063", "red group reporting, target destroyed" },
            { "15064", "blue group reporting, target destroyed" },
            { "15065", "green group reporting, target destroyed" },
            { "15066", "gold group reporting, target destroyed" },
            { "15067", "ship destroyed, repeat ship destroyed" },
            { "15068", "task force 1 reporting, ship destroyed" },
            { "15069", "task force 2 reporting, ship destroyed" },
            { "15070", "task force 3 reporting, ship destroyed" },
            { "15071", "task force 4 reporting, ship destroyed" },
            { "15072", "task force 5 reporting, ship destroyed" },
            { "15073", "task force 6 reporting, ship destroyed" },
            { "15074", "task force 7 reporting, ship destroyed" },
            { "15075", "task force 8 reporting, ship destroyed" },
            { "15076", "red group reporting, taking losses" },
            { "15077", "blue group reporting, taking losses" },
            { "15078", "green group reporting, taking losses" },
            { "15079", "gold group reporting, taking losses" },
            { "15080", "red group reporting, all fighters launched, ready for orders" },
            { "15081", "blue group reporting, all fighters launched, ready for orders" },
            { "15082", "green group reporting, all fighters launched, ready for orders" },
            { "15083", "gold group reporting, all fighters launched, ready for orders" },
            { "15084", "task force 1 acknowledges, assuming formation" },
            { "15085", "task force 2 acknowledges, assuming formation" },
            { "15086", "task force 3 acknowledges, assuming formation" },
            { "15087", "task force 4 acknowledges, assuming formation" },
            { "15088", "task force 5 acknowledges, assuming formation" },
            { "15089", "task force 6 acknowledges, assuming formation" },
            { "15090", "task force 7 acknowledges, assuming formation" },
            { "15091", "task force 8 acknowledges, assuming formation" },
            { "15092", "ship acknowledges mission assignment" },
            { "15093", "task force 1 acknowledges mission assignment" },
            { "15094", "task force 3 acknowledges mission assignment" },
            { "15095", "task force 3 acknowledges mission assignment" },
            { "15096", "task force 4 acknowledges mission assignment" },
            { "15097", "task force 5 acknowledges mission assignment" },
            { "15098", "task force 6 acknowledges mission assignment" },
            { "15099", "task force 7 acknowledges mission assignment" },
            { "15100", "task force 8 acknowledges mission assignment" },
            { "15101", "red group acknowledges mission assignment" },
            { "15102", "blue group acknowledges mission assignment" },
            { "15103", "green group acknowledges mission assignment" },
            { "15104", "gold group acknowledges mission assignment" },
            { "15105", "command ciruits are filled to capacity, no new task forces can be formed, assigned ships will assume orders individually" },
            { "15106", "personnel ejecting from fighters, recovery will be required after the battle" },
            { "15107", "personnel forced to abandon ship, recovery will be required after the battle" },
            { "15108", "red group reporting, remaining fighters recovered" },
            { "15109", "blue group reporting, remaining fighters recovered" },
            { "15110", "green group reporting, remaining fighters recovered" },
            { "15111", "gold group reporting, remaining fighters recovered" },
            { "15112", "red group reporting, unable to recover all fighters, there is not enough docking space available on the remaining ships" },
            { "15113", "blue group reporting, unable to recover all fighters, there is not enough docking space available on the remaining ships" },
            { "15114", "green group reporting, unable to recover all fighters, there is not enough docking space available on the remaining ships" },
            { "15115", "gold group reporting, unable to recover all fighters, there is not enough docking space available on the remaining ships" },
            { "15116", "all units reporting in, the fleet is preparing to make the jump into hyperspace" },
            { "15117", "some ships report that they can not make the jump into hyperspace, the fleet withdrawl will force their crews to scuttle them" },
            { "15118", "not all fighter groups have been recovered, a fleet withdrawl will leave them stranded" },
            { "15119", "not all fighters could be recovered because of a shortage of docking space, a withdrawl will leave them stranded" },
            { "15120", "death star acknowledges, target designated, firing" },
            { "15121", "death star reports, super laser recharging" },
            { "15122", "death star reports, super laser fully charged and ready to fire" },
            { "15123", "death star reports, unable to engage target, line of fire is blocked by other vessels" },
            { "15124", "death star reports, they're under attack by rebel fighters" },
            { "15125", "death star reports, rebel fighters have broken off their attack" },
            { "15126", "the death star it's...it's been destroyed" },
            { "15127", "the fleet has executed the jump into hyperspace, the withdrawl is complete" },
            { "15128", "the rebel fleet is withdrawing, the empire is victorious" },
            { "15129", "the rebel fleet has been destroyed, the empire is victorious" },
            { "15130", "our fleet has been destroyed, the rebels have won the battle" },
            { "15131", "we do not have sufficient fighters to adequately shield the death star, the rebels may launch an attack" },
            { "15132", "death star reports, rebel fighters are continuing to attack" },
        };
    }
}
